"use strict";
/**
 * Redemption & Reward Email Templates
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.generateRedemptionShippedEmail = exports.generateRedemptionApprovedEmail = exports.generateRedemptionRequestEmail = void 0;
// Redemption Request Submitted
function generateRedemptionRequestEmail(userName, rewardName, pointsCost, requestId) {
    var subject = '🎁 Redemption Request Received - Mindful Champion';
    var html = "\n<!DOCTYPE html>\n<html>\n<head>\n  <meta charset=\"utf-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n</head>\n<body style=\"margin: 0; padding: 0; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f5f5f5;\">\n  <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color: #f5f5f5; padding: 20px 0;\">\n    <tr>\n      <td align=\"center\">\n        <table width=\"600\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color: #ffffff; border-radius: 12px; overflow: hidden;\">\n          <tr>\n            <td style=\"background: linear-gradient(135deg, #14b8a6 0%, #0891b2 100%); padding: 40px 20px; text-align: center;\">\n              <h1 style=\"color: #ffffff; margin: 0; font-size: 28px;\">\uD83C\uDF81 Redemption Request Received!</h1>\n            </td>\n          </tr>\n          <tr>\n            <td style=\"padding: 40px 30px;\">\n              <h2 style=\"color: #0f172a; margin: 0 0 20px 0;\">Thanks, ".concat(userName, "! \uD83C\uDF89</h2>\n              <p style=\"color: #334155; font-size: 16px; line-height: 1.6;\">We've received your redemption request for <strong>").concat(rewardName, "</strong>.</p>\n              \n              <div style=\"background: #f0fdfa; padding: 20px; border-radius: 8px; margin: 30px 0;\">\n                <h3 style=\"color: #0f172a; margin: 0 0 15px 0;\">Request Details</h3>\n                <p style=\"color: #334155; margin: 5px 0;\"><strong>Reward:</strong> ").concat(rewardName, "</p>\n                <p style=\"color: #334155; margin: 5px 0;\"><strong>Points Redeemed:</strong> ").concat(pointsCost, " points</p>\n                <p style=\"color: #334155; margin: 5px 0;\"><strong>Request ID:</strong> <span style=\"font-family: monospace; font-size: 12px;\">").concat(requestId, "</span></p>\n              </div>\n              \n              <div style=\"background: #fef3c7; border-left: 4px solid #f59e0b; padding: 20px; border-radius: 8px; margin: 30px 0;\">\n                <p style=\"color: #92400e; margin: 0;\">\uD83D\uDD52 The sponsor will review your request and approve it shortly. You'll receive an email confirmation once it's approved.</p>\n              </div>\n              \n              <div style=\"text-align: center; margin: 30px 0;\">\n                <a href=\"https://mindfulchampion.com/rewards\" style=\"display: inline-block; background: linear-gradient(135deg, #14b8a6 0%, #0891b2 100%); color: #ffffff; text-decoration: none; padding: 16px 40px; border-radius: 8px; font-size: 16px; font-weight: bold;\">View My Rewards \u2192</a>\n              </div>\n            </td>\n          </tr>\n        </table>\n      </td>\n    </tr>\n  </table>\n</body>\n</html>\n  ");
    var text = "Redemption Request Received\n\nThanks, ".concat(userName, "!\n\nWe've received your request for ").concat(rewardName, ".\n\nDetails:\n- Reward: ").concat(rewardName, "\n- Points: ").concat(pointsCost, "\n- Request ID: ").concat(requestId, "\n\nThe sponsor will review shortly.\n\nView rewards: https://mindfulchampion.com/rewards");
    return { subject: subject, html: html, text: text };
}
exports.generateRedemptionRequestEmail = generateRedemptionRequestEmail;
// Redemption Approved
function generateRedemptionApprovedEmail(userName, rewardName, sponsorName, instructions) {
    var subject = '✅ Redemption Approved - Mindful Champion';
    var html = "\n<!DOCTYPE html>\n<html>\n<head>\n  <meta charset=\"utf-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n</head>\n<body style=\"margin: 0; padding: 0; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f5f5f5;\">\n  <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color: #f5f5f5; padding: 20px 0;\">\n    <tr>\n      <td align=\"center\">\n        <table width=\"600\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color: #ffffff; border-radius: 12px; overflow: hidden;\">\n          <tr>\n            <td style=\"background: linear-gradient(135deg, #10b981 0%, #059669 100%); padding: 40px 20px; text-align: center;\">\n              <h1 style=\"color: #ffffff; margin: 0; font-size: 32px;\">\u2705 Redemption Approved!</h1>\n            </td>\n          </tr>\n          <tr>\n            <td style=\"padding: 40px 30px;\">\n              <h2 style=\"color: #0f172a; margin: 0 0 20px 0;\">Great news, ".concat(userName, "! \uD83C\uDF89</h2>\n              <p style=\"color: #334155; font-size: 16px; line-height: 1.6;\">Your redemption request for <strong>").concat(rewardName, "</strong> has been approved by ").concat(sponsorName, "!</p>\n              \n              <div style=\"background: #ecfdf5; border-left: 4px solid #10b981; padding: 20px; border-radius: 8px; margin: 30px 0;\">\n                <h3 style=\"color: #065f46; margin: 0 0 15px 0;\">\uD83C\uDFAF How to Claim Your Reward</h3>\n                <p style=\"color: #064e3b; line-height: 1.8; margin: 0;\">").concat(instructions, "</p>\n              </div>\n              \n              <p style=\"color: #64748b; font-size: 14px; line-height: 1.6; margin: 20px 0;\">\nIf you have any questions about claiming your reward, please contact ").concat(sponsorName, " directly or reach out to our support team.\n              </p>\n              \n              <div style=\"text-align: center; margin: 30px 0;\">\n                <a href=\"https://mindfulchampion.com/rewards\" style=\"display: inline-block; background: linear-gradient(135deg, #10b981 0%, #059669 100%); color: #ffffff; text-decoration: none; padding: 16px 40px; border-radius: 8px; font-size: 16px; font-weight: bold;\">View My Rewards \u2192</a>\n              </div>\n            </td>\n          </tr>\n        </table>\n      </td>\n    </tr>\n  </table>\n</body>\n</html>\n  ");
    var text = "Redemption Approved!\n\nGreat news, ".concat(userName, "!\n\nYour request for ").concat(rewardName, " has been approved by ").concat(sponsorName, ".\n\nHow to Claim:\n").concat(instructions, "\n\nView rewards: https://mindfulchampion.com/rewards");
    return { subject: subject, html: html, text: text };
}
exports.generateRedemptionApprovedEmail = generateRedemptionApprovedEmail;
// Redemption Shipped
function generateRedemptionShippedEmail(userName, rewardName, trackingNumber, carrier, estimatedDelivery) {
    var subject = '🚚 Reward Shipped - Mindful Champion';
    var html = "\n<!DOCTYPE html>\n<html>\n<head>\n  <meta charset=\"utf-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n</head>\n<body style=\"margin: 0; padding: 0; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f5f5f5;\">\n  <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color: #f5f5f5; padding: 20px 0;\">\n    <tr>\n      <td align=\"center\">\n        <table width=\"600\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color: #ffffff; border-radius: 12px; overflow: hidden;\">\n          <tr>\n            <td style=\"background: linear-gradient(135deg, #14b8a6 0%, #0891b2 100%); padding: 40px 20px; text-align: center;\">\n              <h1 style=\"color: #ffffff; margin: 0; font-size: 32px;\">\uD83D\uDE9A Your Reward is On the Way!</h1>\n            </td>\n          </tr>\n          <tr>\n            <td style=\"padding: 40px 30px;\">\n              <h2 style=\"color: #0f172a; margin: 0 0 20px 0;\">Exciting news, ".concat(userName, "! \uD83C\uDF81</h2>\n              <p style=\"color: #334155; font-size: 16px; line-height: 1.6;\">Your <strong>").concat(rewardName, "</strong> has been shipped and is on its way to you!</p>\n              \n              <div style=\"background: #f0fdfa; padding: 20px; border-radius: 8px; margin: 30px 0;\">\n                <h3 style=\"color: #0f172a; margin: 0 0 15px 0;\">\uD83D\uDCE6 Shipping Details</h3>\n                <p style=\"color: #334155; margin: 8px 0;\"><strong>Carrier:</strong> ").concat(carrier, "</p>\n                <p style=\"color: #334155; margin: 8px 0;\"><strong>Tracking Number:</strong></p>\n                <p style=\"color: #14b8a6; font-family: monospace; font-size: 18px; font-weight: bold; margin: 5px 0 15px 0;\">").concat(trackingNumber, "</p>\n                <p style=\"color: #334155; margin: 8px 0;\"><strong>Estimated Delivery:</strong> ").concat(estimatedDelivery, "</p>\n              </div>\n              \n              <div style=\"text-align: center; margin: 30px 0;\">\n                <a href=\"https://tools.usps.com/go/TrackConfirmAction?qtc_tLabels1=").concat(trackingNumber, "\" style=\"display: inline-block; background: linear-gradient(135deg, #14b8a6 0%, #0891b2 100%); color: #ffffff; text-decoration: none; padding: 16px 40px; border-radius: 8px; font-size: 16px; font-weight: bold;\">Track Package \u2192</a>\n              </div>\n              \n              <div style=\"background: #fef3c7; border-left: 4px solid #f59e0b; padding: 20px; border-radius: 8px; margin: 30px 0;\">\n                <p style=\"color: #92400e; margin: 0;\">\uD83D\uDCE7 Make sure someone is available to receive the package. If you have any delivery issues, please contact the carrier directly using the tracking number above.</p>\n              </div>\n            </td>\n          </tr>\n        </table>\n      </td>\n    </tr>\n  </table>\n</body>\n</html>\n  ");
    var text = "Reward Shipped!\n\nExciting news, ".concat(userName, "!\n\nYour ").concat(rewardName, " has been shipped!\n\nShipping Details:\n- Carrier: ").concat(carrier, "\n- Tracking: ").concat(trackingNumber, "\n- Estimated Delivery: ").concat(estimatedDelivery, "\n\nTrack your package: https://tools.usps.com/go/TrackConfirmAction?qtc_tLabels1=").concat(trackingNumber);
    return { subject: subject, html: html, text: text };
}
exports.generateRedemptionShippedEmail = generateRedemptionShippedEmail;
