"use strict";
/**
 * Subscription Email Templates
 * All subscription-related emails
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.generatePaymentReceiptEmail = exports.generateSubscriptionCancelledEmail = exports.generateSubscriptionExpiringEmail = exports.generateSubscriptionConfirmationEmail = void 0;
// Subscription Confirmation
function generateSubscriptionConfirmationEmail(userName, planName, amount, billingDate) {
    var subject = '✅ Subscription Confirmed - Mindful Champion Pro';
    var html = "\n<!DOCTYPE html>\n<html>\n<head>\n  <meta charset=\"utf-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n</head>\n<body style=\"margin: 0; padding: 0; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f5f5f5;\">\n  <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color: #f5f5f5; padding: 20px 0;\">\n    <tr>\n      <td align=\"center\">\n        <table width=\"600\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.1);\">\n          <tr>\n            <td style=\"background: linear-gradient(135deg, #14b8a6 0%, #0891b2 100%); padding: 40px 20px; text-align: center;\">\n              <h1 style=\"color: #ffffff; margin: 0; font-size: 32px;\">\u2705 Subscription Confirmed!</h1>\n            </td>\n          </tr>\n          <tr>\n            <td style=\"padding: 40px 30px;\">\n              <h2 style=\"color: #0f172a; margin: 0 0 20px 0;\">Hey ".concat(userName, "! \uD83C\uDF89</h2>\n              <p style=\"color: #334155; font-size: 16px; line-height: 1.6;\">Welcome to <strong>").concat(planName, "</strong>! Your subscription is now active and you have full access to all premium features.</p>\n              \n              <div style=\"background: #f0fdfa; padding: 20px; border-radius: 8px; margin: 30px 0;\">\n                <h3 style=\"color: #0f172a; margin: 0 0 15px 0;\">\uD83D\uDCCB Subscription Details</h3>\n                <p style=\"color: #334155; margin: 5px 0;\"><strong>Plan:</strong> ").concat(planName, "</p>\n                <p style=\"color: #334155; margin: 5px 0;\"><strong>Amount:</strong> $").concat(amount.toFixed(2), "/month</p>\n                <p style=\"color: #334155; margin: 5px 0;\"><strong>Next Billing:</strong> ").concat(billingDate, "</p>\n              </div>\n              \n              <div style=\"text-align: center; margin: 30px 0;\">\n                <a href=\"https://mindfulchampion.com/dashboard\" style=\"display: inline-block; background: linear-gradient(135deg, #14b8a6 0%, #0891b2 100%); color: #ffffff; text-decoration: none; padding: 16px 40px; border-radius: 8px; font-size: 16px; font-weight: bold;\">Go to Dashboard \u2192</a>\n              </div>\n            </td>\n          </tr>\n          <tr>\n            <td style=\"background-color: #f8fafc; padding: 30px; text-align: center;\">\n              <p style=\"color: #64748b; font-size: 14px; margin: 0;\">Questions? <a href=\"mailto:support@mindfulchampion.com\" style=\"color: #14b8a6;\">Contact Support</a></p>\n            </td>\n          </tr>\n        </table>\n      </td>\n    </tr>\n  </table>\n</body>\n</html>\n  ");
    var text = "Subscription Confirmed - Mindful Champion\n\nHey ".concat(userName, "!\n\nWelcome to ").concat(planName, "! Your subscription is now active.\n\nDetails:\n- Plan: ").concat(planName, "\n- Amount: $").concat(amount.toFixed(2), "/month\n- Next Billing: ").concat(billingDate, "\n\nGo to Dashboard: https://mindfulchampion.com/dashboard");
    return { subject: subject, html: html, text: text };
}
exports.generateSubscriptionConfirmationEmail = generateSubscriptionConfirmationEmail;
// Subscription Expiring
function generateSubscriptionExpiringEmail(userName, planName, expiryDate, daysLeft) {
    var subject = "\u23F0 Your ".concat(planName, " expires in ").concat(daysLeft, " days");
    var html = "\n<!DOCTYPE html>\n<html>\n<head>\n  <meta charset=\"utf-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n</head>\n<body style=\"margin: 0; padding: 0; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f5f5f5;\">\n  <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color: #f5f5f5; padding: 20px 0;\">\n    <tr>\n      <td align=\"center\">\n        <table width=\"600\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color: #ffffff; border-radius: 12px; overflow: hidden;\">\n          <tr>\n            <td style=\"background: linear-gradient(135deg, #f59e0b 0%, #dc2626 100%); padding: 40px 20px; text-align: center;\">\n              <h1 style=\"color: #ffffff; margin: 0; font-size: 28px;\">\u23F0 Subscription Expiring Soon</h1>\n            </td>\n          </tr>\n          <tr>\n            <td style=\"padding: 40px 30px;\">\n              <h2 style=\"color: #0f172a; margin: 0 0 20px 0;\">Hey ".concat(userName, "!</h2>\n              <p style=\"color: #334155; font-size: 16px; line-height: 1.6;\">Your <strong>").concat(planName, "</strong> subscription will expire in <strong style=\"color: #dc2626;\">").concat(daysLeft, " days</strong> on ").concat(expiryDate, ".</p>\n              \n              <div style=\"background: #fef2f2; border-left: 4px solid #dc2626; padding: 20px; border-radius: 8px; margin: 30px 0;\">\n                <p style=\"color: #7f1d1d; margin: 0;\">\u26A0\uFE0F Don't lose access to premium features! Renew now to keep enjoying AI-powered coaching, unlimited video analysis, and exclusive training programs.</p>\n              </div>\n              \n              <div style=\"text-align: center; margin: 30px 0;\">\n                <a href=\"https://mindfulchampion.com/subscription\" style=\"display: inline-block; background: linear-gradient(135deg, #14b8a6 0%, #0891b2 100%); color: #ffffff; text-decoration: none; padding: 16px 40px; border-radius: 8px; font-size: 16px; font-weight: bold;\">Renew Subscription \u2192</a>\n              </div>\n            </td>\n          </tr>\n        </table>\n      </td>\n    </tr>\n  </table>\n</body>\n</html>\n  ");
    var text = "Subscription Expiring - Mindful Champion\n\nHey ".concat(userName, "!\n\nYour ").concat(planName, " subscription will expire in ").concat(daysLeft, " days on ").concat(expiryDate, ".\n\nRenew now: https://mindfulchampion.com/subscription");
    return { subject: subject, html: html, text: text };
}
exports.generateSubscriptionExpiringEmail = generateSubscriptionExpiringEmail;
// Subscription Cancelled
function generateSubscriptionCancelledEmail(userName, planName, endDate) {
    var subject = '❌ Subscription Cancelled - Mindful Champion';
    var html = "\n<!DOCTYPE html>\n<html>\n<head>\n  <meta charset=\"utf-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n</head>\n<body style=\"margin: 0; padding: 0; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f5f5f5;\">\n  <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color: #f5f5f5; padding: 20px 0;\">\n    <tr>\n      <td align=\"center\">\n        <table width=\"600\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color: #ffffff; border-radius: 12px; overflow: hidden;\">\n          <tr>\n            <td style=\"background: linear-gradient(135deg, #64748b 0%, #475569 100%); padding: 40px 20px; text-align: center;\">\n              <h1 style=\"color: #ffffff; margin: 0; font-size: 28px;\">Subscription Cancelled</h1>\n            </td>\n          </tr>\n          <tr>\n            <td style=\"padding: 40px 30px;\">\n              <h2 style=\"color: #0f172a; margin: 0 0 20px 0;\">Hey ".concat(userName, ",</h2>\n              <p style=\"color: #334155; font-size: 16px; line-height: 1.6;\">We're sorry to see you go! Your <strong>").concat(planName, "</strong> subscription has been cancelled.</p>\n              \n              <div style=\"background: #f8fafc; padding: 20px; border-radius: 8px; margin: 30px 0;\">\n                <p style=\"color: #334155; margin: 0;\">You'll continue to have access to premium features until <strong>").concat(endDate, "</strong>. After that, your account will be downgraded to the free plan.</p>\n              </div>\n              \n              <p style=\"color: #334155; font-size: 16px; line-height: 1.6;\">We'd love to have you back! If you change your mind or have feedback on how we can improve, please let us know.</p>\n              \n              <div style=\"text-align: center; margin: 30px 0;\">\n                <a href=\"https://mindfulchampion.com/subscription\" style=\"display: inline-block; background: linear-gradient(135deg, #14b8a6 0%, #0891b2 100%); color: #ffffff; text-decoration: none; padding: 16px 40px; border-radius: 8px; font-size: 16px; font-weight: bold;\">Reactivate Subscription \u2192</a>\n              </div>\n            </td>\n          </tr>\n        </table>\n      </td>\n    </tr>\n  </table>\n</body>\n</html>\n  ");
    var text = "Subscription Cancelled - Mindful Champion\n\nHey ".concat(userName, ",\n\nYour ").concat(planName, " subscription has been cancelled. You'll have access until ").concat(endDate, ".\n\nReactivate anytime: https://mindfulchampion.com/subscription");
    return { subject: subject, html: html, text: text };
}
exports.generateSubscriptionCancelledEmail = generateSubscriptionCancelledEmail;
// Payment Receipt
function generatePaymentReceiptEmail(userName, amount, planName, transactionId, date) {
    var subject = '🧾 Payment Receipt - Mindful Champion';
    var html = "\n<!DOCTYPE html>\n<html>\n<head>\n  <meta charset=\"utf-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n</head>\n<body style=\"margin: 0; padding: 0; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f5f5f5;\">\n  <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color: #f5f5f5; padding: 20px 0;\">\n    <tr>\n      <td align=\"center\">\n        <table width=\"600\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color: #ffffff; border-radius: 12px; overflow: hidden;\">\n          <tr>\n            <td style=\"background: linear-gradient(135deg, #14b8a6 0%, #0891b2 100%); padding: 40px 20px; text-align: center;\">\n              <h1 style=\"color: #ffffff; margin: 0; font-size: 28px;\">\uD83E\uDDFE Payment Receipt</h1>\n            </td>\n          </tr>\n          <tr>\n            <td style=\"padding: 40px 30px;\">\n              <h2 style=\"color: #0f172a; margin: 0 0 20px 0;\">Thank you, ".concat(userName, "!</h2>\n              <p style=\"color: #334155; font-size: 16px; line-height: 1.6;\">Your payment has been successfully processed.</p>\n              \n              <div style=\"background: #f0fdfa; padding: 20px; border-radius: 8px; margin: 30px 0;\">\n                <h3 style=\"color: #0f172a; margin: 0 0 15px 0;\">Payment Details</h3>\n                <table width=\"100%\" style=\"color: #334155; font-size: 14px;\">\n                  <tr>\n                    <td style=\"padding: 8px 0;\"><strong>Amount:</strong></td>\n                    <td style=\"text-align: right;\">$").concat(amount.toFixed(2), "</td>\n                  </tr>\n                  <tr>\n                    <td style=\"padding: 8px 0;\"><strong>Plan:</strong></td>\n                    <td style=\"text-align: right;\">").concat(planName, "</td>\n                  </tr>\n                  <tr>\n                    <td style=\"padding: 8px 0;\"><strong>Date:</strong></td>\n                    <td style=\"text-align: right;\">").concat(date, "</td>\n                  </tr>\n                  <tr>\n                    <td style=\"padding: 8px 0;\"><strong>Transaction ID:</strong></td>\n                    <td style=\"text-align: right; font-family: monospace; font-size: 12px;\">").concat(transactionId, "</td>\n                  </tr>\n                </table>\n              </div>\n              \n              <p style=\"color: #64748b; font-size: 14px; margin: 20px 0 0 0;\">Keep this receipt for your records. If you have any questions about this payment, please contact our support team.</p>\n            </td>\n          </tr>\n        </table>\n      </td>\n    </tr>\n  </table>\n</body>\n</html>\n  ");
    var text = "Payment Receipt - Mindful Champion\n\nThank you, ".concat(userName, "!\n\nPayment Details:\n- Amount: $").concat(amount.toFixed(2), "\n- Plan: ").concat(planName, "\n- Date: ").concat(date, "\n- Transaction ID: ").concat(transactionId);
    return { subject: subject, html: html, text: text };
}
exports.generatePaymentReceiptEmail = generatePaymentReceiptEmail;
