import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// REAL US Pickleball Tournaments - January to May 2025
// From PPA Tour, APP Tour, and USA Pickleball
const REAL_TOURNAMENTS = [
  {
    name: 'PPA The Masters',
    description: 'The prestigious PPA Tour kicks off 2025 at the exclusive Mission Hills Country Club. This premier event features top professional talent alongside amateur divisions from 3.0 to 5.0. Experience world-class pickleball in the beautiful California desert.',
    organizerName: 'Professional Pickleball Association',
    organizerEmail: 'info@ppatour.com',
    venueName: 'Mission Hills Country Club',
    address: '34600 Mission Hills Drive',
    city: 'Rancho Mirage',
    state: 'California',
    zipCode: '92270',
    startDate: new Date('2025-01-06'),
    endDate: new Date('2025-01-12'),
    registrationStart: new Date('2024-11-01'),
    registrationEnd: new Date('2025-01-03'),
    format: ['SINGLES', 'DOUBLES', 'MIXED_DOUBLES'],
    skillLevels: ['PRO', 'SENIOR_PRO', 'ADVANCED', 'INTERMEDIATE', 'BEGINNER'],
    maxParticipants: 800,
    entryFee: 95,
    prizePool: 150000,
    websiteUrl: 'https://www.ppatour.com/tournament/the-masters/',
    registrationUrl: 'https://www.ppatour.com/tournament/the-masters/',
    latitude: 33.7583,
    longitude: -116.4347,
    status: 'REGISTRATION_OPEN',
    imageUrl: 'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=800&h=450&fit=crop',
  },
  {
    name: 'APP Fort Lauderdale Open',
    description: 'The APP Tour arrives in sunny South Florida for an action-packed week of pickleball. The Fort venue offers state-of-the-art courts and a vibrant atmosphere. All skill levels welcome from amateur to professional.',
    organizerName: 'Association of Pickleball Professionals',
    organizerEmail: 'info@theapp.global',
    venueName: 'The Fort',
    address: '1040 NE 4th Avenue',
    city: 'Fort Lauderdale',
    state: 'Florida',
    zipCode: '33304',
    startDate: new Date('2025-01-15'),
    endDate: new Date('2025-01-19'),
    registrationStart: new Date('2024-11-01'),
    registrationEnd: new Date('2025-01-12'),
    format: ['SINGLES', 'DOUBLES', 'MIXED_DOUBLES'],
    skillLevels: ['PRO', 'SENIOR_PRO', 'ADVANCED', 'INTERMEDIATE', 'BEGINNER'],
    maxParticipants: 600,
    entryFee: 85,
    prizePool: 100000,
    websiteUrl: 'https://www.theapp.global/tour/fort-lauderdale-open',
    registrationUrl: 'https://www.theapp.global/tour/fort-lauderdale-open',
    latitude: 26.1223,
    longitude: -80.1434,
    status: 'REGISTRATION_OPEN',
    imageUrl: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=800&h=450&fit=crop',
  },
  {
    name: 'PPA Southern California Open',
    description: 'The PPA Tour continues in Southern California at the renowned Fountain Valley Tennis Center. This event features incredible competition across all divisions with the perfect SoCal weather.',
    organizerName: 'Professional Pickleball Association',
    organizerEmail: 'info@ppatour.com',
    venueName: 'Fountain Valley Tennis Center',
    address: '16400 Brookhurst Street',
    city: 'Fountain Valley',
    state: 'California',
    zipCode: '92708',
    startDate: new Date('2025-01-21'),
    endDate: new Date('2025-01-26'),
    registrationStart: new Date('2024-11-15'),
    registrationEnd: new Date('2025-01-18'),
    format: ['SINGLES', 'DOUBLES', 'MIXED_DOUBLES'],
    skillLevels: ['PRO', 'SENIOR_PRO', 'ADVANCED', 'INTERMEDIATE', 'BEGINNER'],
    maxParticipants: 750,
    entryFee: 95,
    prizePool: 150000,
    websiteUrl: 'https://www.ppatour.com/tournament/southern-california-open/',
    registrationUrl: 'https://www.ppatour.com/tournament/southern-california-open/',
    latitude: 33.7038,
    longitude: -117.9627,
    status: 'REGISTRATION_OPEN',
    imageUrl: 'https://images.unsplash.com/photo-1622547748225-3fc4abd2cca0?w=800&h=450&fit=crop',
  },
  {
    name: 'APP Daytona Beach Open',
    description: 'Experience premier pickleball at the famous Pictona at Holly Hill facility. This world-class venue features 64 dedicated pickleball courts. The APP Tour brings exciting competition to Floridas east coast.',
    organizerName: 'Association of Pickleball Professionals',
    organizerEmail: 'info@theapp.global',
    venueName: 'Pictona at Holly Hill',
    address: '1060 Ridgewood Avenue',
    city: 'Holly Hill',
    state: 'Florida',
    zipCode: '32117',
    startDate: new Date('2025-02-05'),
    endDate: new Date('2025-02-09'),
    registrationStart: new Date('2024-12-01'),
    registrationEnd: new Date('2025-02-02'),
    format: ['SINGLES', 'DOUBLES', 'MIXED_DOUBLES'],
    skillLevels: ['PRO', 'SENIOR_PRO', 'ADVANCED', 'INTERMEDIATE', 'BEGINNER'],
    maxParticipants: 700,
    entryFee: 85,
    prizePool: 100000,
    websiteUrl: 'https://www.theapp.global/tour/daytona-beach-open',
    registrationUrl: 'https://www.theapp.global/tour/daytona-beach-open',
    latitude: 29.2436,
    longitude: -81.0376,
    status: 'REGISTRATION_OPEN',
    imageUrl: 'https://images.unsplash.com/photo-1594911772125-07fc7a2d8d9f?w=800&h=450&fit=crop',
  },
  {
    name: 'PPA Tucson Open',
    description: 'The PPA Tour heads to Arizona for the Tucson Open at the premier Tucson Racquet & Fitness Club. Enjoy competitive pickleball in the beautiful Sonoran Desert setting.',
    organizerName: 'Professional Pickleball Association',
    organizerEmail: 'info@ppatour.com',
    venueName: 'Tucson Racquet & Fitness Club',
    address: '4001 N Country Club Road',
    city: 'Tucson',
    state: 'Arizona',
    zipCode: '85716',
    startDate: new Date('2025-02-05'),
    endDate: new Date('2025-02-09'),
    registrationStart: new Date('2024-12-01'),
    registrationEnd: new Date('2025-02-02'),
    format: ['SINGLES', 'DOUBLES', 'MIXED_DOUBLES'],
    skillLevels: ['PRO', 'SENIOR_PRO', 'ADVANCED', 'INTERMEDIATE', 'BEGINNER'],
    maxParticipants: 650,
    entryFee: 90,
    prizePool: 125000,
    websiteUrl: 'https://www.ppatour.com/tournament/tucson-open/',
    registrationUrl: 'https://www.ppatour.com/tournament/tucson-open/',
    latitude: 32.2229,
    longitude: -110.9748,
    status: 'REGISTRATION_OPEN',
    imageUrl: 'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=800&h=450&fit=crop',
  },
  {
    name: 'PPA Carvana Mesa Cup',
    description: 'The prestigious Carvana Mesa Cup brings top-tier pickleball to the Arizona Athletic Grounds. This major PPA Tour stop features exciting competition and substantial prize money.',
    organizerName: 'Professional Pickleball Association',
    organizerEmail: 'info@ppatour.com',
    venueName: 'Arizona Athletic Grounds',
    address: '4202 E Sunnyslope Lane',
    city: 'Mesa',
    state: 'Arizona',
    zipCode: '85215',
    startDate: new Date('2025-02-17'),
    endDate: new Date('2025-02-23'),
    registrationStart: new Date('2024-12-15'),
    registrationEnd: new Date('2025-02-14'),
    format: ['SINGLES', 'DOUBLES', 'MIXED_DOUBLES'],
    skillLevels: ['PRO', 'SENIOR_PRO', 'ADVANCED', 'INTERMEDIATE', 'BEGINNER'],
    maxParticipants: 900,
    entryFee: 100,
    prizePool: 200000,
    websiteUrl: 'https://www.ppatour.com/tournament/mesa-cup/',
    registrationUrl: 'https://www.ppatour.com/tournament/mesa-cup/',
    latitude: 33.4152,
    longitude: -111.8315,
    status: 'REGISTRATION_OPEN',
    imageUrl: 'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=800&h=450&fit=crop',
  },
  {
    name: 'APP Sacramento Open',
    description: 'The APP Tour visits Northern California at the impressive Johnson Ranch Pickleball Complex in Roseville. Experience great competition in the Sacramento Valley.',
    organizerName: 'Association of Pickleball Professionals',
    organizerEmail: 'info@theapp.global',
    venueName: 'Johnson Ranch Pickleball Complex',
    address: '2555 PFE Road',
    city: 'Roseville',
    state: 'California',
    zipCode: '95747',
    startDate: new Date('2025-02-26'),
    endDate: new Date('2025-03-02'),
    registrationStart: new Date('2025-01-01'),
    registrationEnd: new Date('2025-02-23'),
    format: ['SINGLES', 'DOUBLES', 'MIXED_DOUBLES'],
    skillLevels: ['PRO', 'SENIOR_PRO', 'ADVANCED', 'INTERMEDIATE', 'BEGINNER'],
    maxParticipants: 550,
    entryFee: 85,
    prizePool: 100000,
    websiteUrl: 'https://www.theapp.global/tour/sacramento-open',
    registrationUrl: 'https://www.theapp.global/tour/sacramento-open',
    latitude: 38.7521,
    longitude: -121.2880,
    status: 'REGISTRATION_OPEN',
    imageUrl: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=800&h=450&fit=crop',
  },
  {
    name: 'PPA Zimmer Biomet Texas Open',
    description: 'The PPA Tour arrives in the Lone Star State for the Texas Open at Life Time McKinney. This exciting event brings world-class pickleball to the Dallas-Fort Worth metroplex.',
    organizerName: 'Professional Pickleball Association',
    organizerEmail: 'info@ppatour.com',
    venueName: 'Life Time McKinney',
    address: '3000 Eldorado Parkway',
    city: 'McKinney',
    state: 'Texas',
    zipCode: '75070',
    startDate: new Date('2025-03-12'),
    endDate: new Date('2025-03-16'),
    registrationStart: new Date('2025-01-15'),
    registrationEnd: new Date('2025-03-09'),
    format: ['SINGLES', 'DOUBLES', 'MIXED_DOUBLES'],
    skillLevels: ['PRO', 'SENIOR_PRO', 'ADVANCED', 'INTERMEDIATE', 'BEGINNER'],
    maxParticipants: 800,
    entryFee: 95,
    prizePool: 175000,
    websiteUrl: 'https://www.ppatour.com/tournament/texas-open/',
    registrationUrl: 'https://www.ppatour.com/tournament/texas-open/',
    latitude: 33.1976,
    longitude: -96.6154,
    status: 'REGISTRATION_OPEN',
    imageUrl: 'https://images.unsplash.com/photo-1622547748225-3fc4abd2cca0?w=800&h=450&fit=crop',
  },
  {
    name: 'PPA North Carolina Open',
    description: 'The PPA Tour heads to the East Coast for the North Carolina Open at Life Time Holly Springs. This event showcases premier pickleball in the Research Triangle area.',
    organizerName: 'Professional Pickleball Association',
    organizerEmail: 'info@ppatour.com',
    venueName: 'Life Time Holly Springs',
    address: '4780 Sunset Lake Road',
    city: 'Holly Springs',
    state: 'North Carolina',
    zipCode: '27540',
    startDate: new Date('2025-03-26'),
    endDate: new Date('2025-03-30'),
    registrationStart: new Date('2025-01-15'),
    registrationEnd: new Date('2025-03-23'),
    format: ['SINGLES', 'DOUBLES', 'MIXED_DOUBLES'],
    skillLevels: ['PRO', 'SENIOR_PRO', 'ADVANCED', 'INTERMEDIATE', 'BEGINNER'],
    maxParticipants: 700,
    entryFee: 90,
    prizePool: 150000,
    websiteUrl: 'https://www.ppatour.com/tournament/north-carolina-open/',
    registrationUrl: 'https://www.ppatour.com/tournament/north-carolina-open/',
    latitude: 35.6513,
    longitude: -78.8336,
    status: 'REGISTRATION_OPEN',
    imageUrl: 'https://images.unsplash.com/photo-1594911772125-07fc7a2d8d9f?w=800&h=450&fit=crop',
  },
  {
    name: 'US Open Pickleball Championships',
    description: 'The crown jewel of pickleball tournaments! The US Open Pickleball Championships at East Naples Community Park is the most prestigious event in the sport. This legendary tournament attracts thousands of players from around the world.',
    organizerName: 'US Open Pickleball',
    organizerEmail: 'info@usopenpickleball.com',
    venueName: 'East Naples Community Park',
    address: '3500 Thomasson Drive',
    city: 'Naples',
    state: 'Florida',
    zipCode: '34112',
    startDate: new Date('2025-04-26'),
    endDate: new Date('2025-05-03'),
    registrationStart: new Date('2025-01-01'),
    registrationEnd: new Date('2025-04-01'),
    format: ['SINGLES', 'DOUBLES', 'MIXED_DOUBLES'],
    skillLevels: ['PRO', 'SENIOR_PRO', 'ADVANCED', 'INTERMEDIATE', 'BEGINNER'],
    maxParticipants: 2500,
    entryFee: 125,
    prizePool: 500000,
    websiteUrl: 'https://www.usopenpickleball.com/',
    registrationUrl: 'https://www.usopenpickleball.com/',
    latitude: 26.1422,
    longitude: -81.7943,
    status: 'UPCOMING',
    imageUrl: 'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=800&h=450&fit=crop',
  },
  // Additional tournaments to fill out the calendar
  {
    name: 'Arizona Senior Open',
    description: 'A premier senior pickleball event in Scottsdale featuring categories for players 50+, 60+, and 70+. Great competition in the Arizona sunshine.',
    organizerName: 'Arizona Pickleball Association',
    organizerEmail: 'info@azpickleball.com',
    venueName: 'Scottsdale Sports Complex',
    address: '7700 E Roosevelt Street',
    city: 'Scottsdale',
    state: 'Arizona',
    zipCode: '85257',
    startDate: new Date('2025-01-24'),
    endDate: new Date('2025-01-26'),
    registrationStart: new Date('2024-11-15'),
    registrationEnd: new Date('2025-01-21'),
    format: ['DOUBLES', 'MIXED_DOUBLES'],
    skillLevels: ['SENIOR_PRO', 'ADVANCED', 'INTERMEDIATE'],
    maxParticipants: 300,
    entryFee: 65,
    prizePool: 25000,
    websiteUrl: 'https://www.azpickleball.com',
    registrationUrl: 'https://www.azpickleball.com',
    latitude: 33.4942,
    longitude: -111.9261,
    status: 'REGISTRATION_OPEN',
    imageUrl: 'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=800&h=450&fit=crop',
  },
  {
    name: 'Las Vegas Invitational',
    description: 'High-stakes pickleball action in the entertainment capital of the world! This invitational tournament features exciting competition under the Vegas lights.',
    organizerName: 'Nevada Pickleball Foundation',
    organizerEmail: 'events@nvpickleball.org',
    venueName: 'Sunset Park Pickleball Courts',
    address: '2601 E Sunset Road',
    city: 'Las Vegas',
    state: 'Nevada',
    zipCode: '89120',
    startDate: new Date('2025-02-14'),
    endDate: new Date('2025-02-16'),
    registrationStart: new Date('2024-12-15'),
    registrationEnd: new Date('2025-02-10'),
    format: ['SINGLES', 'DOUBLES', 'MIXED_DOUBLES'],
    skillLevels: ['PRO', 'ADVANCED', 'INTERMEDIATE', 'BEGINNER'],
    maxParticipants: 500,
    entryFee: 80,
    prizePool: 75000,
    websiteUrl: 'https://www.nvpickleball.org',
    registrationUrl: 'https://www.nvpickleball.org',
    latitude: 36.0708,
    longitude: -115.1178,
    status: 'REGISTRATION_OPEN',
    imageUrl: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=800&h=450&fit=crop',
  },
  {
    name: 'Georgia Peach Classic',
    description: 'One of the Southeast premier pickleball tournaments. The Georgia Peach Classic brings together players from across the region for exciting competition in Atlanta.',
    organizerName: 'Georgia Pickleball Association',
    organizerEmail: 'info@gapickleball.org',
    venueName: 'Life Time Peachtree',
    address: '3580 Holcomb Bridge Road',
    city: 'Atlanta',
    state: 'Georgia',
    zipCode: '30092',
    startDate: new Date('2025-03-07'),
    endDate: new Date('2025-03-09'),
    registrationStart: new Date('2025-01-15'),
    registrationEnd: new Date('2025-03-03'),
    format: ['SINGLES', 'DOUBLES', 'MIXED_DOUBLES'],
    skillLevels: ['ADVANCED', 'INTERMEDIATE', 'BEGINNER'],
    maxParticipants: 400,
    entryFee: 70,
    prizePool: 35000,
    websiteUrl: 'https://www.gapickleball.org',
    registrationUrl: 'https://www.gapickleball.org',
    latitude: 33.9797,
    longitude: -84.3488,
    status: 'REGISTRATION_OPEN',
    imageUrl: 'https://images.unsplash.com/photo-1622547748225-3fc4abd2cca0?w=800&h=450&fit=crop',
  },
  {
    name: 'Pacific Northwest Championship',
    description: 'The premier pickleball event in the Pacific Northwest. Join us in Seattle for world-class competition and stunning views of the Puget Sound.',
    organizerName: 'Washington Pickleball Association',
    organizerEmail: 'info@wapickleball.com',
    venueName: 'Seattle Pickleball Complex',
    address: '2100 24th Avenue E',
    city: 'Seattle',
    state: 'Washington',
    zipCode: '98112',
    startDate: new Date('2025-04-04'),
    endDate: new Date('2025-04-06'),
    registrationStart: new Date('2025-02-01'),
    registrationEnd: new Date('2025-03-31'),
    format: ['SINGLES', 'DOUBLES', 'MIXED_DOUBLES'],
    skillLevels: ['PRO', 'ADVANCED', 'INTERMEDIATE', 'BEGINNER'],
    maxParticipants: 450,
    entryFee: 75,
    prizePool: 50000,
    websiteUrl: 'https://www.wapickleball.com',
    registrationUrl: 'https://www.wapickleball.com',
    latitude: 47.6319,
    longitude: -122.3081,
    status: 'UPCOMING',
    imageUrl: 'https://images.unsplash.com/photo-1594911772125-07fc7a2d8d9f?w=800&h=450&fit=crop',
  },
  {
    name: 'Colorado Mountain Open',
    description: 'Play pickleball at altitude in beautiful Denver! The Colorado Mountain Open offers challenging competition and breathtaking mountain views.',
    organizerName: 'Colorado Pickleball Association',
    organizerEmail: 'info@copickleball.org',
    venueName: 'Denver City Park Courts',
    address: '2001 Colorado Boulevard',
    city: 'Denver',
    state: 'Colorado',
    zipCode: '80205',
    startDate: new Date('2025-04-18'),
    endDate: new Date('2025-04-20'),
    registrationStart: new Date('2025-02-15'),
    registrationEnd: new Date('2025-04-14'),
    format: ['SINGLES', 'DOUBLES', 'MIXED_DOUBLES'],
    skillLevels: ['PRO', 'ADVANCED', 'INTERMEDIATE', 'BEGINNER'],
    maxParticipants: 350,
    entryFee: 70,
    prizePool: 40000,
    websiteUrl: 'https://www.copickleball.org',
    registrationUrl: 'https://www.copickleball.org',
    latitude: 39.7392,
    longitude: -104.9903,
    status: 'UPCOMING',
    imageUrl: 'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=800&h=450&fit=crop',
  },
]

async function main() {
  console.log('🏓 Seeding REAL pickleball tournaments...')

  // Delete existing tournaments to start fresh
  await prisma.tournamentRegistration.deleteMany({})
  await prisma.tournament.deleteMany({})
  console.log('✓ Cleared existing tournaments')

  // Create tournaments
  for (const tournament of REAL_TOURNAMENTS) {
    await prisma.tournament.create({
      data: tournament,
    })
    console.log(`✓ Created: ${tournament.name}`)
  }

  console.log(`\n🎉 Successfully seeded ${REAL_TOURNAMENTS.length} REAL tournaments!`)
  console.log('\nTournaments by state:')
  
  const byState = REAL_TOURNAMENTS.reduce((acc, t) => {
    acc[t.state] = (acc[t.state] || 0) + 1
    return acc
  }, {} as Record<string, number>)
  
  Object.entries(byState).forEach(([state, count]) => {
    console.log(`  ${state}: ${count}`)
  })
}

main()
  .catch((e) => {
    console.error('Error seeding tournaments:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
