import { PrismaClient } from '@prisma/client';
import { SkillLevel, TournamentStatus, TournamentFormat } from '@prisma/client';

const prisma = new PrismaClient();

const tournaments = [
  {
    name: 'Miami Open Pickleball Championship',
    description: 'Premier pickleball tournament featuring top players from across the Southeast. Professional-grade courts, live streaming, and substantial prize pool.',
    organizerName: 'Florida Pickleball Association',
    organizerEmail: 'events@floridapickleball.org',
    organizerPhone: '(305) 555-0123',
    status: TournamentStatus.UPCOMING,
    venueName: 'Miami Beach Sports Complex',
    address: '2301 Collins Avenue',
    city: 'Miami Beach',
    state: 'FL',
    zipCode: '33139',
    country: 'USA',
    latitude: 25.7932,
    longitude: -80.1305,
    startDate: new Date('2026-02-15'),
    endDate: new Date('2026-02-17'),
    registrationStart: new Date('2025-12-01'),
    registrationEnd: new Date('2026-02-08'),
    format: [TournamentFormat.DOUBLES, TournamentFormat.SINGLES, TournamentFormat.MIXED_DOUBLES],
    skillLevels: [SkillLevel.ADVANCED, SkillLevel.PRO, SkillLevel.PRO],
    maxParticipants: 256,
    currentRegistrations: 187,
    entryFee: 125.00,
    prizePool: 25000.00,
    websiteUrl: 'https://miamiopen.pickleballchampionships.com',
    registrationUrl: 'https://miamiopen.pickleballchampionships.com/register',
    imageUrl: 'https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800&h=600&fit=crop'
  },
  {
    name: 'Austin City Limits Pickleball Classic',
    description: 'Join us for three days of competitive pickleball in the heart of Texas! Open to all skill levels with separate brackets.',
    organizerName: 'Texas Pickleball Federation',
    organizerEmail: 'info@texaspickleball.com',
    organizerPhone: '(512) 555-0145',
    status: TournamentStatus.UPCOMING,
    venueName: 'Zilker Park Recreation Center',
    address: '2100 Barton Springs Road',
    city: 'Austin',
    state: 'TX',
    zipCode: '78704',
    country: 'USA',
    latitude: 30.2640,
    longitude: -97.7736,
    startDate: new Date('2026-03-20'),
    endDate: new Date('2026-03-22'),
    registrationStart: new Date('2026-01-01'),
    registrationEnd: new Date('2026-03-13'),
    format: [TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
    skillLevels: [SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED, SkillLevel.PRO],
    maxParticipants: 180,
    currentRegistrations: 92,
    entryFee: 85.00,
    prizePool: 12000.00,
    websiteUrl: 'https://austinpickleball.com/acl-classic',
    registrationUrl: 'https://austinpickleball.com/acl-classic/register',
    imageUrl: 'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=800&h=600&fit=crop'
  },
  {
    name: 'San Diego Coastal Cup',
    description: 'Beautiful oceanfront venue with indoor/outdoor courts. Perfect weather guaranteed! Family-friendly tournament.',
    organizerName: 'Southern California Pickleball League',
    organizerEmail: 'coastal@socalpickleball.org',
    organizerPhone: '(619) 555-0198',
    status: TournamentStatus.UPCOMING,
    venueName: 'Pacific Beach Recreation Center',
    address: '1405 Diamond Street',
    city: 'San Diego',
    state: 'CA',
    zipCode: '92109',
    country: 'USA',
    latitude: 32.7968,
    longitude: -117.2283,
    startDate: new Date('2026-01-25'),
    endDate: new Date('2026-01-26'),
    registrationStart: new Date('2025-12-10'),
    registrationEnd: new Date('2026-01-18'),
    format: [TournamentFormat.DOUBLES],
    skillLevels: [SkillLevel.BEGINNER, SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED],
    maxParticipants: 120,
    currentRegistrations: 108,
    entryFee: 65.00,
    prizePool: 5000.00,
    websiteUrl: 'https://coastalcup.socalpickleball.org',
    registrationUrl: 'https://coastalcup.socalpickleball.org/register',
    imageUrl: 'https://images.unsplash.com/photo-1587280501635-68a0e82cd5ff?w=800&h=600&fit=crop'
  },
  {
    name: 'Denver Mountain State Championships',
    description: 'High-altitude tournament featuring Colorado\'s best players. State championship qualifications on the line.',
    organizerName: 'Colorado Pickleball Association',
    organizerEmail: 'championships@coloradopickleball.com',
    organizerPhone: '(303) 555-0176',
    status: TournamentStatus.UPCOMING,
    venueName: 'Gates Tennis Center',
    address: '3300 E Bayaud Avenue',
    city: 'Denver',
    state: 'CO',
    zipCode: '80209',
    country: 'USA',
    latitude: 39.7152,
    longitude: -104.9561,
    startDate: new Date('2026-04-10'),
    endDate: new Date('2026-04-12'),
    registrationStart: new Date('2026-02-01'),
    registrationEnd: new Date('2026-04-03'),
    format: [TournamentFormat.SINGLES, TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
    skillLevels: [SkillLevel.ADVANCED, SkillLevel.PRO, SkillLevel.PRO],
    maxParticipants: 200,
    currentRegistrations: 145,
    entryFee: 100.00,
    prizePool: 15000.00,
    websiteUrl: 'https://championships.coloradopickleball.com',
    registrationUrl: 'https://championships.coloradopickleball.com/register',
    imageUrl: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=800&h=600&fit=crop'
  },
  {
    name: 'Phoenix Desert Challenge',
    description: 'Beat the heat with early morning and evening sessions. Air-conditioned indoor courts available.',
    organizerName: 'Arizona Pickleball Network',
    organizerEmail: 'desert@azpickleball.net',
    organizerPhone: '(602) 555-0134',
    status: TournamentStatus.UPCOMING,
    venueName: 'Scottsdale Ranch Park',
    address: '10400 E Via Linda',
    city: 'Scottsdale',
    state: 'AZ',
    zipCode: '85258',
    country: 'USA',
    latitude: 33.6119,
    longitude: -111.8910,
    startDate: new Date('2026-02-28'),
    endDate: new Date('2026-03-02'),
    registrationStart: new Date('2026-01-05'),
    registrationEnd: new Date('2026-02-21'),
    format: [TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
    skillLevels: [SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED],
    maxParticipants: 160,
    currentRegistrations: 78,
    entryFee: 75.00,
    prizePool: 8000.00,
    websiteUrl: 'https://desertchallenge.azpickleball.net',
    registrationUrl: 'https://desertchallenge.azpickleball.net/register',
    imageUrl: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800&h=600&fit=crop'
  },
  {
    name: 'Seattle Emerald City Open',
    description: 'Pacific Northwest\'s premier indoor pickleball event. Rain or shine, we\'re playing!',
    organizerName: 'Pacific Northwest Pickleball Association',
    organizerEmail: 'emerald@pnwpickleball.org',
    organizerPhone: '(206) 555-0187',
    status: TournamentStatus.UPCOMING,
    venueName: 'Seattle Center Arena',
    address: '305 Harrison Street',
    city: 'Seattle',
    state: 'WA',
    zipCode: '98109',
    country: 'USA',
    latitude: 47.6219,
    longitude: -122.3517,
    startDate: new Date('2026-03-06'),
    endDate: new Date('2026-03-08'),
    registrationStart: new Date('2026-01-10'),
    registrationEnd: new Date('2026-02-27'),
    format: [TournamentFormat.SINGLES, TournamentFormat.DOUBLES],
    skillLevels: [SkillLevel.ADVANCED, SkillLevel.PRO, SkillLevel.PRO],
    maxParticipants: 240,
    currentRegistrations: 156,
    entryFee: 110.00,
    prizePool: 18000.00,
    websiteUrl: 'https://emeraldcityopen.com',
    registrationUrl: 'https://emeraldcityopen.com/register',
    imageUrl: 'https://images.unsplash.com/photo-1519766304817-4f37bda74a26?w=800&h=600&fit=crop'
  },
  {
    name: 'Chicago Windy City Showdown',
    description: 'Midwest\'s largest pickleball tournament with over 300 participants. Multiple venues across the city.',
    organizerName: 'Chicago Metro Pickleball Association',
    organizerEmail: 'showdown@chicagopickleball.com',
    organizerPhone: '(312) 555-0165',
    status: TournamentStatus.UPCOMING,
    venueName: 'McFetridge Sports Complex',
    address: '3843 N California Avenue',
    city: 'Chicago',
    state: 'IL',
    zipCode: '60618',
    country: 'USA',
    latitude: 41.9553,
    longitude: -87.6971,
    startDate: new Date('2026-05-15'),
    endDate: new Date('2026-05-17'),
    registrationStart: new Date('2026-03-01'),
    registrationEnd: new Date('2026-05-08'),
    format: [TournamentFormat.DOUBLES, TournamentFormat.SINGLES, TournamentFormat.MIXED_DOUBLES],
    skillLevels: [SkillLevel.BEGINNER, SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED, SkillLevel.PRO],
    maxParticipants: 320,
    currentRegistrations: 234,
    entryFee: 90.00,
    prizePool: 20000.00,
    websiteUrl: 'https://windycityshowdown.com',
    registrationUrl: 'https://windycityshowdown.com/register',
    imageUrl: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&h=600&fit=crop'
  },
  {
    name: 'Atlanta Southern Classic',
    description: 'Experience southern hospitality while competing at the highest level. BBQ and live music included!',
    organizerName: 'Georgia Pickleball Federation',
    organizerEmail: 'classic@georgiapickleball.org',
    organizerPhone: '(404) 555-0142',
    status: TournamentStatus.UPCOMING,
    venueName: 'Piedmont Park Tennis Center',
    address: '1099 Piedmont Avenue NE',
    city: 'Atlanta',
    state: 'GA',
    zipCode: '30309',
    country: 'USA',
    latitude: 33.7866,
    longitude: -84.3733,
    startDate: new Date('2026-04-24'),
    endDate: new Date('2026-04-26'),
    registrationStart: new Date('2026-02-15'),
    registrationEnd: new Date('2026-04-17'),
    format: [TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
    skillLevels: [SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED, SkillLevel.PRO],
    maxParticipants: 200,
    currentRegistrations: 167,
    entryFee: 80.00,
    prizePool: 10000.00,
    websiteUrl: 'https://southernclassic.com',
    registrationUrl: 'https://southernclassic.com/register',
    imageUrl: 'https://images.unsplash.com/photo-1444723121867-7a241cacace9?w=800&h=600&fit=crop'
  },
  {
    name: 'Boston Harbor Challenge',
    description: 'Historic venue with waterfront views. New England\'s most prestigious pickleball event.',
    organizerName: 'New England Pickleball Association',
    organizerEmail: 'harbor@nepickleball.org',
    organizerPhone: '(617) 555-0193',
    status: TournamentStatus.UPCOMING,
    venueName: 'Boston Harbor Yacht Club',
    address: '321 Marginal Street',
    city: 'Boston',
    state: 'MA',
    zipCode: '02128',
    country: 'USA',
    latitude: 42.3736,
    longitude: -71.0260,
    startDate: new Date('2026-06-12'),
    endDate: new Date('2026-06-14'),
    registrationStart: new Date('2026-04-01'),
    registrationEnd: new Date('2026-06-05'),
    format: [TournamentFormat.DOUBLES, TournamentFormat.SINGLES],
    skillLevels: [SkillLevel.ADVANCED, SkillLevel.PRO, SkillLevel.PRO],
    maxParticipants: 180,
    currentRegistrations: 124,
    entryFee: 120.00,
    prizePool: 22000.00,
    websiteUrl: 'https://bostonharborchallenge.com',
    registrationUrl: 'https://bostonharborchallenge.com/register',
    imageUrl: 'https://images.unsplash.com/photo-1494522855154-9297ac14b55f?w=800&h=600&fit=crop'
  },
  {
    name: 'Las Vegas Desert Heat Tournament',
    description: 'What happens in Vegas... gets posted on our leaderboard! Night games under the lights.',
    organizerName: 'Nevada Pickleball League',
    organizerEmail: 'heat@nevadapickleball.com',
    organizerPhone: '(702) 555-0158',
    status: TournamentStatus.UPCOMING,
    venueName: 'Las Vegas Sports Park',
    address: '7900 W Alexander Road',
    city: 'Las Vegas',
    state: 'NV',
    zipCode: '89129',
    country: 'USA',
    latitude: 36.2850,
    longitude: -115.2647,
    startDate: new Date('2026-07-18'),
    endDate: new Date('2026-07-20'),
    registrationStart: new Date('2026-05-01'),
    registrationEnd: new Date('2026-07-11'),
    format: [TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
    skillLevels: [SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED, SkillLevel.PRO],
    maxParticipants: 220,
    currentRegistrations: 145,
    entryFee: 95.00,
    prizePool: 16000.00,
    websiteUrl: 'https://desertheat.nevadapickleball.com',
    registrationUrl: 'https://desertheat.nevadapickleball.com/register',
    imageUrl: 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=800&h=600&fit=crop'
  },
  {
    name: 'Portland Rose City Championship',
    description: 'Eco-friendly tournament with sustainable practices. Food trucks and local breweries on site.',
    organizerName: 'Oregon Pickleball Alliance',
    organizerEmail: 'rosecity@oregonpickleball.org',
    organizerPhone: '(503) 555-0171',
    status: TournamentStatus.UPCOMING,
    venueName: 'Mt. Tabor Park Courts',
    address: '6800 SE Division Street',
    city: 'Portland',
    state: 'OR',
    zipCode: '97206',
    country: 'USA',
    latitude: 45.5115,
    longitude: -122.5933,
    startDate: new Date('2026-08-07'),
    endDate: new Date('2026-08-09'),
    registrationStart: new Date('2026-06-01'),
    registrationEnd: new Date('2026-07-31'),
    format: [TournamentFormat.DOUBLES],
    skillLevels: [SkillLevel.BEGINNER, SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED],
    maxParticipants: 140,
    currentRegistrations: 89,
    entryFee: 70.00,
    prizePool: 7000.00,
    websiteUrl: 'https://rosecity.oregonpickleball.org',
    registrationUrl: 'https://rosecity.oregonpickleball.org/register',
    imageUrl: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&h=600&fit=crop'
  },
  {
    name: 'Nashville Music City Masters',
    description: 'Where pickleball meets country music! Live performances between matches.',
    organizerName: 'Tennessee Pickleball Association',
    organizerEmail: 'masters@tennpickleball.com',
    organizerPhone: '(615) 555-0189',
    status: TournamentStatus.UPCOMING,
    venueName: 'Centennial Sportsplex',
    address: '222 25th Avenue North',
    city: 'Nashville',
    state: 'TN',
    zipCode: '37203',
    country: 'USA',
    latitude: 36.1540,
    longitude: -86.8025,
    startDate: new Date('2026-09-18'),
    endDate: new Date('2026-09-20'),
    registrationStart: new Date('2026-07-01'),
    registrationEnd: new Date('2026-09-11'),
    format: [TournamentFormat.SINGLES, TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
    skillLevels: [SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED, SkillLevel.PRO, SkillLevel.PRO],
    maxParticipants: 280,
    currentRegistrations: 198,
    entryFee: 105.00,
    prizePool: 19000.00,
    websiteUrl: 'https://musiccitymasters.com',
    registrationUrl: 'https://musiccitymasters.com/register',
    imageUrl: 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800&h=600&fit=crop'
  },
  {
    name: 'Philadelphia Liberty Bell Classic',
    description: 'Historic city, historic competition. Indoor climate-controlled venue.',
    organizerName: 'Pennsylvania Pickleball Federation',
    organizerEmail: 'liberty@papickleball.org',
    organizerPhone: '(215) 555-0194',
    status: TournamentStatus.UPCOMING,
    venueName: 'Philadelphia Sports Complex',
    address: '3601 S Broad Street',
    city: 'Philadelphia',
    state: 'PA',
    zipCode: '19148',
    country: 'USA',
    latitude: 39.9082,
    longitude: -75.1670,
    startDate: new Date('2026-10-23'),
    endDate: new Date('2026-10-25'),
    registrationStart: new Date('2026-08-15'),
    registrationEnd: new Date('2026-10-16'),
    format: [TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
    skillLevels: [SkillLevel.ADVANCED, SkillLevel.PRO],
    maxParticipants: 160,
    currentRegistrations: 87,
    entryFee: 85.00,
    prizePool: 11000.00,
    websiteUrl: 'https://libertybellclassic.com',
    registrationUrl: 'https://libertybellclassic.com/register',
    imageUrl: 'https://images.unsplash.com/photo-1499092346589-b9b6be3e94b2?w=800&h=600&fit=crop'
  },
  {
    name: 'Minneapolis Lakes Open',
    description: 'Land of 10,000 lakes hosts premier summer tournament. Lakeside venue with stunning views.',
    organizerName: 'Minnesota Pickleball Association',
    organizerEmail: 'lakes@mnpickleball.org',
    organizerPhone: '(612) 555-0177',
    status: TournamentStatus.UPCOMING,
    venueName: 'Lake Calhoun Beach Club',
    address: '3000 Calhoun Parkway East',
    city: 'Minneapolis',
    state: 'MN',
    zipCode: '55408',
    country: 'USA',
    latitude: 44.9486,
    longitude: -93.3191,
    startDate: new Date('2026-07-10'),
    endDate: new Date('2026-07-12'),
    registrationStart: new Date('2026-05-01'),
    registrationEnd: new Date('2026-07-03'),
    format: [TournamentFormat.DOUBLES],
    skillLevels: [SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED],
    maxParticipants: 150,
    currentRegistrations: 112,
    entryFee: 75.00,
    prizePool: 8500.00,
    websiteUrl: 'https://lakesopen.mnpickleball.org',
    registrationUrl: 'https://lakesopen.mnpickleball.org/register',
    imageUrl: 'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?w=800&h=600&fit=crop'
  },
  {
    name: 'Charlotte Queen City Challenge',
    description: 'Fast-paced tournament in NASCAR country. Speed matters on and off the court!',
    organizerName: 'North Carolina Pickleball League',
    organizerEmail: 'queencity@ncpickleball.com',
    organizerPhone: '(704) 555-0162',
    status: TournamentStatus.UPCOMING,
    venueName: 'Freedom Park Courts',
    address: '1900 East Boulevard',
    city: 'Charlotte',
    state: 'NC',
    zipCode: '28203',
    country: 'USA',
    latitude: 35.2016,
    longitude: -80.8396,
    startDate: new Date('2026-05-29'),
    endDate: new Date('2026-05-31'),
    registrationStart: new Date('2026-03-15'),
    registrationEnd: new Date('2026-05-22'),
    format: [TournamentFormat.SINGLES, TournamentFormat.DOUBLES],
    skillLevels: [SkillLevel.BEGINNER, SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED],
    maxParticipants: 190,
    currentRegistrations: 143,
    entryFee: 70.00,
    prizePool: 9000.00,
    websiteUrl: 'https://queencitychallenge.com',
    registrationUrl: 'https://queencitychallenge.com/register',
    imageUrl: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&h=600&fit=crop'
  },
  {
    name: 'Tampa Bay Sunshine Invitational',
    description: 'Winter warmth and competitive play. Perfect escape from the cold!',
    organizerName: 'Tampa Bay Pickleball Association',
    organizerEmail: 'sunshine@tampapickleball.org',
    organizerPhone: '(813) 555-0183',
    status: TournamentStatus.UPCOMING,
    venueName: 'Curtis Hixon Waterfront Park',
    address: '600 N Ashley Drive',
    city: 'Tampa',
    state: 'FL',
    zipCode: '33602',
    country: 'USA',
    latitude: 27.9492,
    longitude: -82.4616,
    startDate: new Date('2026-01-15'),
    endDate: new Date('2026-01-17'),
    registrationStart: new Date('2025-11-01'),
    registrationEnd: new Date('2026-01-08'),
    format: [TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
    skillLevels: [SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED, SkillLevel.PRO],
    maxParticipants: 200,
    currentRegistrations: 176,
    entryFee: 80.00,
    prizePool: 12000.00,
    websiteUrl: 'https://sunshineinvitational.com',
    registrationUrl: 'https://sunshineinvitational.com/register',
    imageUrl: 'https://images.unsplash.com/photo-1598135753163-6167c1a1ad65?w=800&h=600&fit=crop'
  },
  {
    name: 'Sacramento Capital Cup',
    description: 'California state capital hosts elite competition. Professional referees and live scoring.',
    organizerName: 'Northern California Pickleball Association',
    organizerEmail: 'capital@norcalpickleball.org',
    organizerPhone: '(916) 555-0168',
    status: TournamentStatus.UPCOMING,
    venueName: 'William Land Park Tennis Center',
    address: '701 Freeport Boulevard',
    city: 'Sacramento',
    state: 'CA',
    zipCode: '95822',
    country: 'USA',
    latitude: 38.5482,
    longitude: -121.5065,
    startDate: new Date('2026-04-17'),
    endDate: new Date('2026-04-19'),
    registrationStart: new Date('2026-02-01'),
    registrationEnd: new Date('2026-04-10'),
    format: [TournamentFormat.SINGLES, TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
    skillLevels: [SkillLevel.ADVANCED, SkillLevel.PRO, SkillLevel.PRO],
    maxParticipants: 240,
    currentRegistrations: 189,
    entryFee: 115.00,
    prizePool: 21000.00,
    websiteUrl: 'https://capitalcup.norcalpickleball.org',
    registrationUrl: 'https://capitalcup.norcalpickleball.org/register',
    imageUrl: 'https://images.unsplash.com/photo-1587280501635-68a0e82cd5ff?w=800&h=600&fit=crop'
  },
  {
    name: 'San Antonio Fiesta Open',
    description: 'Celebrate Tex-Mex culture with world-class pickleball. Mariachi bands and authentic cuisine!',
    organizerName: 'San Antonio Pickleball Federation',
    organizerEmail: 'fiesta@sapickleball.com',
    organizerPhone: '(210) 555-0152',
    status: TournamentStatus.UPCOMING,
    venueName: 'McFarlin Tennis Center',
    address: '1503 San Pedro Avenue',
    city: 'San Antonio',
    state: 'TX',
    zipCode: '78212',
    country: 'USA',
    latitude: 29.4508,
    longitude: -98.4940,
    startDate: new Date('2026-06-26'),
    endDate: new Date('2026-06-28'),
    registrationStart: new Date('2026-04-15'),
    registrationEnd: new Date('2026-06-19'),
    format: [TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
    skillLevels: [SkillLevel.BEGINNER, SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED],
    maxParticipants: 170,
    currentRegistrations: 98,
    entryFee: 65.00,
    prizePool: 6500.00,
    websiteUrl: 'https://fiestaopen.com',
    registrationUrl: 'https://fiestaopen.com/register',
    imageUrl: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&h=600&fit=crop'
  },
  {
    name: 'Columbus Buckeye Championship',
    description: 'Ohio\'s premier tournament with Big Ten energy. College town atmosphere.',
    organizerName: 'Ohio Pickleball Association',
    organizerEmail: 'buckeye@ohiopickleball.org',
    organizerPhone: '(614) 555-0174',
    status: TournamentStatus.UPCOMING,
    venueName: 'Griggs Reservoir Park',
    address: '3750 Riverside Drive',
    city: 'Columbus',
    state: 'OH',
    zipCode: '43221',
    country: 'USA',
    latitude: 39.9854,
    longitude: -83.0743,
    startDate: new Date('2026-08-21'),
    endDate: new Date('2026-08-23'),
    registrationStart: new Date('2026-06-15'),
    registrationEnd: new Date('2026-08-14'),
    format: [TournamentFormat.DOUBLES],
    skillLevels: [SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED, SkillLevel.PRO],
    maxParticipants: 200,
    currentRegistrations: 134,
    entryFee: 85.00,
    prizePool: 13000.00,
    websiteUrl: 'https://buckeyechampionship.com',
    registrationUrl: 'https://buckeyechampionship.com/register',
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop'
  },
  {
    name: 'New Orleans Bayou Classic',
    description: 'Jazz, jambalaya, and pickleball! Experience NOLA culture between matches.',
    organizerName: 'Louisiana Pickleball League',
    organizerEmail: 'bayou@louisianapickleball.com',
    organizerPhone: '(504) 555-0196',
    status: TournamentStatus.UPCOMING,
    venueName: 'City Park Tennis Center',
    address: '1 Palm Drive',
    city: 'New Orleans',
    state: 'LA',
    zipCode: '70124',
    country: 'USA',
    latitude: 29.9946,
    longitude: -90.0984,
    startDate: new Date('2026-11-13'),
    endDate: new Date('2026-11-15'),
    registrationStart: new Date('2026-09-01'),
    registrationEnd: new Date('2026-11-06'),
    format: [TournamentFormat.SINGLES, TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
    skillLevels: [SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED, SkillLevel.PRO],
    maxParticipants: 210,
    currentRegistrations: 145,
    entryFee: 90.00,
    prizePool: 14000.00,
    websiteUrl: 'https://bayouclassic.com',
    registrationUrl: 'https://bayouclassic.com/register',
    imageUrl: 'https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=800&h=600&fit=crop'
  },
  {
    name: 'Salt Lake City Mountain West Open',
    description: 'Breathtaking mountain backdrop with world-class facilities. Elevation training optional!',
    organizerName: 'Utah Pickleball Federation',
    organizerEmail: 'mountainwest@utahpickleball.org',
    organizerPhone: '(801) 555-0181',
    status: TournamentStatus.UPCOMING,
    venueName: 'Liberty Park Tennis Complex',
    address: '600 E 900 S',
    city: 'Salt Lake City',
    state: 'UT',
    zipCode: '84102',
    country: 'USA',
    latitude: 40.7425,
    longitude: -111.8706,
    startDate: new Date('2026-09-04'),
    endDate: new Date('2026-09-06'),
    registrationStart: new Date('2026-07-01'),
    registrationEnd: new Date('2026-08-28'),
    format: [TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
    skillLevels: [SkillLevel.ADVANCED, SkillLevel.PRO, SkillLevel.PRO],
    maxParticipants: 180,
    currentRegistrations: 123,
    entryFee: 100.00,
    prizePool: 17000.00,
    websiteUrl: 'https://mountainwestopen.com',
    registrationUrl: 'https://mountainwestopen.com/register',
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop'
  },
  {
    name: 'Raleigh Triangle Tournament',
    description: 'Research Triangle\'s best players compete. Tech sponsors and innovation showcase.',
    organizerName: 'Triangle Pickleball Association',
    organizerEmail: 'triangle@trianglepickleball.org',
    organizerPhone: '(919) 555-0166',
    status: TournamentStatus.UPCOMING,
    venueName: 'Millbrook Exchange Tennis Center',
    address: '1905 Spring Forest Road',
    city: 'Raleigh',
    state: 'NC',
    zipCode: '27615',
    country: 'USA',
    latitude: 35.8436,
    longitude: -78.6066,
    startDate: new Date('2026-10-09'),
    endDate: new Date('2026-10-11'),
    registrationStart: new Date('2026-08-01'),
    registrationEnd: new Date('2026-10-02'),
    format: [TournamentFormat.DOUBLES],
    skillLevels: [SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED],
    maxParticipants: 160,
    currentRegistrations: 94,
    entryFee: 75.00,
    prizePool: 9500.00,
    websiteUrl: 'https://triangletournament.com',
    registrationUrl: 'https://triangletournament.com/register',
    imageUrl: 'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?w=800&h=600&fit=crop'
  },
  {
    name: 'Albuquerque Balloon Fiesta Classic',
    description: 'Play under hot air balloons! Unique high-desert tournament experience.',
    organizerName: 'New Mexico Pickleball Association',
    organizerEmail: 'balloon@nmpickleball.org',
    organizerPhone: '(505) 555-0179',
    status: TournamentStatus.UPCOMING,
    venueName: 'Balloon Fiesta Park',
    address: '5000 Balloon Fiesta Parkway NE',
    city: 'Albuquerque',
    state: 'NM',
    zipCode: '87113',
    country: 'USA',
    latitude: 35.1817,
    longitude: -106.5985,
    startDate: new Date('2026-10-02'),
    endDate: new Date('2026-10-04'),
    registrationStart: new Date('2026-08-01'),
    registrationEnd: new Date('2026-09-25'),
    format: [TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
    skillLevels: [SkillLevel.BEGINNER, SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED],
    maxParticipants: 150,
    currentRegistrations: 87,
    entryFee: 70.00,
    prizePool: 7500.00,
    websiteUrl: 'https://balloonfiesta.nmpickleball.org',
    registrationUrl: 'https://balloonfiesta.nmpickleball.org/register',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=600&fit=crop'
  },
  {
    name: 'Kansas City BBQ & Pickleball Festival',
    description: 'Best BBQ in America meets best pickleball! Competition and cookoff combined.',
    organizerName: 'Greater KC Pickleball League',
    organizerEmail: 'bbq@kcpickleball.com',
    organizerPhone: '(816) 555-0164',
    status: TournamentStatus.UPCOMING,
    venueName: 'Swope Park Tennis Center',
    address: '6501 E 63rd Street',
    city: 'Kansas City',
    state: 'MO',
    zipCode: '64133',
    country: 'USA',
    latitude: 39.0096,
    longitude: -94.5304,
    startDate: new Date('2026-07-31'),
    endDate: new Date('2026-08-02'),
    registrationStart: new Date('2026-06-01'),
    registrationEnd: new Date('2026-07-24'),
    format: [TournamentFormat.DOUBLES],
    skillLevels: [SkillLevel.BEGINNER, SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED],
    maxParticipants: 180,
    currentRegistrations: 126,
    entryFee: 75.00,
    prizePool: 10000.00,
    websiteUrl: 'https://bbqpickleball.com',
    registrationUrl: 'https://bbqpickleball.com/register',
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&h=600&fit=crop'
  },
  {
    name: 'Orlando Theme Park Challenge',
    description: 'Family-friendly tournament near all major attractions. Disney discounts for participants!',
    organizerName: 'Central Florida Pickleball Network',
    organizerEmail: 'themepark@cfpickleball.org',
    organizerPhone: '(407) 555-0192',
    status: TournamentStatus.UPCOMING,
    venueName: 'Lake Baldwin Sports Complex',
    address: '4701 New Broad Street',
    city: 'Orlando',
    state: 'FL',
    zipCode: '32814',
    country: 'USA',
    latitude: 28.5708,
    longitude: -81.3463,
    startDate: new Date('2026-03-13'),
    endDate: new Date('2026-03-15'),
    registrationStart: new Date('2026-01-10'),
    registrationEnd: new Date('2026-03-06'),
    format: [TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
    skillLevels: [SkillLevel.BEGINNER, SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED],
    maxParticipants: 220,
    currentRegistrations: 178,
    entryFee: 80.00,
    prizePool: 11000.00,
    websiteUrl: 'https://themeparkchallenge.com',
    registrationUrl: 'https://themeparkchallenge.com/register',
    imageUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&h=600&fit=crop'
  },
  {
    name: 'Indianapolis Motor Speedway Classic',
    description: 'Fast courts inspired by the Indy 500. Need for speed on the pickleball court!',
    organizerName: 'Indiana Pickleball Association',
    organizerEmail: 'speedway@indianapickleball.org',
    organizerPhone: '(317) 555-0185',
    status: TournamentStatus.UPCOMING,
    venueName: 'Riverside Park Sports Complex',
    address: '2420 E Riverside Drive',
    city: 'Indianapolis',
    state: 'IN',
    zipCode: '46208',
    country: 'USA',
    latitude: 39.7947,
    longitude: -86.1380,
    startDate: new Date('2026-05-08'),
    endDate: new Date('2026-05-10'),
    registrationStart: new Date('2026-03-01'),
    registrationEnd: new Date('2026-05-01'),
    format: [TournamentFormat.SINGLES, TournamentFormat.DOUBLES],
    skillLevels: [SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED, SkillLevel.PRO],
    maxParticipants: 190,
    currentRegistrations: 152,
    entryFee: 85.00,
    prizePool: 13500.00,
    websiteUrl: 'https://speedwayclassic.com',
    registrationUrl: 'https://speedwayclassic.com/register',
    imageUrl: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&h=600&fit=crop'
  },
  {
    name: 'Virginia Beach Coastal Championship',
    description: 'Beach resort tournament with ocean breezes. Volleyball meets pickleball vibes!',
    organizerName: 'Virginia Pickleball Federation',
    organizerEmail: 'coastal@virginiapickleball.org',
    organizerPhone: '(757) 555-0173',
    status: TournamentStatus.UPCOMING,
    venueName: 'Virginia Beach Sports Center',
    address: '2181 Landstown Road',
    city: 'Virginia Beach',
    state: 'VA',
    zipCode: '23456',
    country: 'USA',
    latitude: 36.7968,
    longitude: -76.0449,
    startDate: new Date('2026-06-05'),
    endDate: new Date('2026-06-07'),
    registrationStart: new Date('2026-04-01'),
    registrationEnd: new Date('2026-05-29'),
    format: [TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
    skillLevels: [SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED],
    maxParticipants: 170,
    currentRegistrations: 118,
    entryFee: 75.00,
    prizePool: 9000.00,
    websiteUrl: 'https://coastalchampionship.com',
    registrationUrl: 'https://coastalchampionship.com/register',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=600&fit=crop'
  },
  {
    name: 'Milwaukee Brew City Tournament',
    description: 'Beer capital hosts pickleball championship. Local brewery tours for participants!',
    organizerName: 'Wisconsin Pickleball League',
    organizerEmail: 'brewcity@wipickleball.com',
    organizerPhone: '(414) 555-0188',
    status: TournamentStatus.UPCOMING,
    venueName: 'Humboldt Park Tennis Courts',
    address: '3000 S Howell Avenue',
    city: 'Milwaukee',
    state: 'WI',
    zipCode: '53207',
    country: 'USA',
    latitude: 43.0116,
    longitude: -87.8938,
    startDate: new Date('2026-08-28'),
    endDate: new Date('2026-08-30'),
    registrationStart: new Date('2026-06-15'),
    registrationEnd: new Date('2026-08-21'),
    format: [TournamentFormat.DOUBLES],
    skillLevels: [SkillLevel.BEGINNER, SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED],
    maxParticipants: 160,
    currentRegistrations: 101,
    entryFee: 70.00,
    prizePool: 8000.00,
    websiteUrl: 'https://brewcitytournament.com',
    registrationUrl: 'https://brewcitytournament.com/register',
    imageUrl: 'https://images.unsplash.com/photo-1436076863939-06870fe779c2?w=800&h=600&fit=crop'
  },
  {
    name: 'Honolulu Pacific Islands Open',
    description: 'Paradise tournament with tropical views. Play in paradise!',
    organizerName: 'Hawaii Pickleball Association',
    organizerEmail: 'aloha@hawaiipickleball.org',
    organizerPhone: '(808) 555-0199',
    status: TournamentStatus.UPCOMING,
    venueName: 'Ala Moana Beach Park Courts',
    address: '1201 Ala Moana Boulevard',
    city: 'Honolulu',
    state: 'HI',
    zipCode: '96814',
    country: 'USA',
    latitude: 21.2896,
    longitude: -157.8437,
    startDate: new Date('2026-11-20'),
    endDate: new Date('2026-11-22'),
    registrationStart: new Date('2026-09-15'),
    registrationEnd: new Date('2026-11-13'),
    format: [TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
    skillLevels: [SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED, SkillLevel.PRO],
    maxParticipants: 140,
    currentRegistrations: 86,
    entryFee: 150.00,
    prizePool: 20000.00,
    websiteUrl: 'https://pacificislandsopen.com',
    registrationUrl: 'https://pacificislandsopen.com/register',
    imageUrl: 'https://images.unsplash.com/photo-1542259009477-d625272157b7?w=800&h=600&fit=crop'
  },
  {
    name: 'Tucson Desert Oasis Championship',
    description: 'Saguaro cactus backdrop with championship-level competition. Desert beauty meets athletic excellence.',
    organizerName: 'Southern Arizona Pickleball League',
    organizerEmail: 'oasis@southernazpickleball.org',
    organizerPhone: '(520) 555-0169',
    status: TournamentStatus.UPCOMING,
    venueName: 'Reffkin Tennis Center',
    address: '50 E Elm Street',
    city: 'Tucson',
    state: 'AZ',
    zipCode: '85705',
    country: 'USA',
    latitude: 32.2384,
    longitude: -110.9594,
    startDate: new Date('2026-12-04'),
    endDate: new Date('2026-12-06'),
    registrationStart: new Date('2026-10-01'),
    registrationEnd: new Date('2026-11-27'),
    format: [TournamentFormat.SINGLES, TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
    skillLevels: [SkillLevel.ADVANCED, SkillLevel.PRO, SkillLevel.PRO],
    maxParticipants: 210,
    currentRegistrations: 134,
    entryFee: 105.00,
    prizePool: 18000.00,
    websiteUrl: 'https://desertoasis.southernazpickleball.org',
    registrationUrl: 'https://desertoasis.southernazpickleball.org/register',
    imageUrl: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&h=600&fit=crop'
  }
];

async function main() {
  console.log('🎾 Starting tournament seeding...');

  // Clear existing tournaments
  console.log('🗑️  Clearing existing tournaments...');
  await prisma.tournament.deleteMany({});

  // Seed tournaments
  console.log('✨ Seeding tournaments...');
  for (const tournament of tournaments) {
    await prisma.tournament.create({
      data: tournament
    });
  }

  console.log(`✅ Successfully seeded ${tournaments.length} tournaments!`);

  // Display summary
  const tournamentCount = await prisma.tournament.count();
  const upcomingCount = await prisma.tournament.count({
    where: { status: TournamentStatus.UPCOMING }
  });
  const statesCount = await prisma.tournament.groupBy({
    by: ['state'],
    _count: true
  });

  console.log('\n📊 Tournament Summary:');
  console.log(`   Total Tournaments: ${tournamentCount}`);
  console.log(`   Upcoming: ${upcomingCount}`);
  console.log(`   States Covered: ${statesCount.length}`);
  console.log('\n🗺️  Tournaments by State:');
  statesCount.forEach(({ state, _count }) => {
    console.log(`   ${state}: ${_count}`);
  });
}

main()
  .catch((e) => {
    console.error('❌ Error seeding tournaments:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
