// @ts-nocheck
/**
 * TOURNAMENT PREPARATION - Complete 21-Day Advanced Training Program
 * Get tournament-ready with mental, physical, and strategic training
 */

export const tournamentPrepProgram = {
  programId: 'advanced-tournament-prep',
  name: 'Tournament Preparation',
  tagline: 'Get tournament-ready with mental and physical training',
  description: 'Complete tournament preparation covering match strategy, mental game, physical conditioning, and competitive scenarios. This 21-day advanced program simulates tournament conditions, teaches you to peak on game day, manage bracket play across multiple matches, and perform under pressure when it matters most.',
  durationDays: 21,
  skillLevel: 'ADVANCED',
  estimatedTimePerDay: '60 minutes',
  whyThisMatters: 'Tournament pickleball is completely different from recreational play. The pressure, fatigue, and strategic depth require specific preparation. This program ensures you show up tournament-ready, not just hoping your skills translate under pressure.',
  nextProgram: 'Elite Mastery Program',
  keyOutcomes: [
    'Develop tournament-ready mental toughness',
    'Master match strategy and game planning',
    'Build physical endurance for long matches',
    'Handle pressure situations with confidence',
    'Execute all skills consistently in competition'
  ],
  dailyStructure: {
    days: Array.from({ length: 21 }, (_, i) => {
      const weekTopics = [
        // Week 1: Mental Game & Strategy (Days 1-7)
        ['Mental Preparation Basics', 'Pre-Match Routines', 'Between-Point Rituals', 'Handling Pressure', 'Visualization Techniques', 'Focus & Concentration', 'Mental Resilience'],
        // Week 2: Physical & Technical (Days 8-14)
        ['Physical Conditioning', 'Endurance Training', 'Quick Recovery Techniques', 'Technical Consistency', 'Shot Selection Strategy', 'Partner Communication', 'Doubles Positioning'],
        // Week 3: Competition Prep (Days 15-21)
        ['Match Simulation', 'Bracket Play Strategy', 'Adapting to Opponents', 'Handling Different Conditions', 'Tournament Day Preparation', 'Peak Performance', 'Championship Mindset']
      ];
      const weekIndex = Math.floor(i / 7);
      const dayInWeek = i % 7;
      
      return {
        day: i + 1,
        title: `Day ${i + 1}: ${weekTopics[weekIndex][dayInWeek]}`,
        focus: [
          'Building mental foundation for competition',
          'Developing consistent pre-match routine',
          'Creating effective between-point rituals',
          'Learning to perform under pressure',
          'Using visualization for success',
          'Maintaining focus during long matches',
          'Building mental toughness and resilience',
          'Improving cardiovascular endurance',
          'Building match-length stamina',
          'Recovering quickly between games',
          'Executing shots consistently under pressure',
          'Making smart shot selections in competition',
          'Optimizing doubles communication',
          'Mastering doubles positioning strategy',
          'Simulating real match conditions',
          'Understanding bracket strategy and pacing',
          'Adapting game plan to different opponents',
          'Playing in various court conditions',
          'Perfecting tournament day routine',
          'Achieving peak performance state',
          'Developing championship-level mentality'
        ][i],
        description: [
          'Build the mental foundation for tournament success. Learn mindfulness, positive self-talk, and mental preparation techniques.',
          'Develop a consistent pre-match routine that prepares you physically and mentally for competition.',
          'Create effective between-point rituals that help you reset, refocus, and maintain composure.',
          'Practice performing under pressure through simulated high-stakes scenarios and mental training.',
          'Master visualization techniques to mentally rehearse success and build confidence.',
          'Develop laser focus that lasts through long matches and multiple games per day.',
          'Build mental resilience to bounce back from losses, mistakes, and adversity.',
          'Improve cardiovascular fitness for sustained performance in long matches.',
          'Build stamina to maintain peak performance throughout entire tournaments.',
          'Learn quick recovery techniques for playing multiple matches per day.',
          'Practice executing all shots with consistency when fatigue and pressure are high.',
          'Develop strategic shot selection skills that win points efficiently.',
          'Optimize communication with doubles partners for seamless coordination.',
          'Master doubles positioning for defensive and offensive situations.',
          'Play full match simulations that replicate tournament intensity and duration.',
          'Learn bracket strategy: when to conserve energy, when to go all-out.',
          'Practice adapting your game plan based on opponent strengths and weaknesses.',
          'Train in various conditions: outdoor/indoor, wind, sun, different court surfaces.',
          'Perfect your tournament day routine from wake-up to first serve.',
          'Learn to achieve peak performance state through pre-competition rituals.',
          'Develop the championship mindset that separates winners from competitors.'
        ][i],
        duration_minutes: 60,
        videoUrl: `https://www.youtube.com/watch?v=${['1Nhnz8brZRA', '_ew47Dqi-3w', 'P06TNWpWU9k', 'l8AzqCNxDTI', 'SuDAwDyy3g4', 'I7Xl4w9vy2U', 'bJkWCJkquXw', 'rD1O3R9B0Sw', '2Vk-c8TdC28', 'mAKQtndtp5s', 'D6e5EW7ze48', 'nXzfAQki67E', 'ZIqR6rFX0lw', '40ap9ZC7EdI', 'Vptpa0FfS5U', 'a5gTSrUHqzU', 'AuZ3DaTTYrw', 'VKR6XWj2DLs', 'pUR6ToL21aU', '_swDF_6b9qw', '1Nhnz8brZRA'][i]}`,
        videoTitle: weekTopics[weekIndex][dayInWeek],
        warmup: {
          title: 'Tournament Prep Warm-up',
          exercises: [
            '10 minutes cardio (match simulation intensity)',
            'Dynamic stretching - full body',
            'Mental preparation exercises',
            'Visualization practice',
            'Progressive skill warm-up (dinking → driving → games)',
            'Partner coordination drills'
          ],
          duration_minutes: 15
        },
        main_drills: [
          {
            name: `Primary Training - Day ${i + 1}`,
            description: [
              'Mental skills workshop: mindfulness meditation, positive self-talk practice, mental imagery.',
              'Pre-match routine development: warm-up sequence, equipment check, mental prep.',
              'Between-point ritual practice: breathing exercises, reset routine, positive reinforcement.',
              'Pressure simulation: play points with consequences, sudden-death scenarios, crowd noise.',
              'Guided visualization: winning scenarios, successful shot execution, trophy ceremonies.',
              'Focus training: long rallies with concentration, distraction resistance drills.',
              'Resilience building: comeback scenarios, play from behind, mental reset after errors.',
              'Cardio circuit: high-intensity intervals simulating rally intensity.',
              'Endurance matches: play continuous games with minimal rest between.',
              'Recovery protocol: stretching, hydration, nutrition, mental decompression.',
              'Consistency drills: execute 100 serves, 100 returns, 100 dinks with 85%+ success.',
              'Shot selection games: points only count with smart shot choices.',
              'Communication drills: call every ball, constant strategy discussion, partner signals.',
              'Positioning scenarios: defensive positioning, offensive positioning, transition positioning.',
              'Full match simulation: play complete 11-point games with tournament rules.',
              'Bracket strategy games: some games at 70% effort, others at 100%.',
              'Opponent adaptation: switch opponents every game, adjust strategy each time.',
              'Condition training: play in wind, sun, shade, different court surfaces.',
              'Tournament day simulation: follow complete routine from wake to play.',
              'Peak state training: pre-performance routine, optimal arousal level, flow state practice.',
              'Championship scenarios: play for titles, handle match point, pressure performances.'
            ][i],
            duration_minutes: 30,
            reps_or_sets: [
              '3 x 10-minute mental practice sessions',
              '5 complete pre-match routine rehearsals',
              '50 points with ritual practice',
              '40 high-pressure points',
              '4 x 5-minute visualization sessions',
              '5 x 15-minute focus rally sessions',
              '30 comeback scenario points',
              '30 minutes HIIT cardio',
              '3 x 20-minute continuous play sessions',
              '45-minute recovery session',
              '100 each of 3 shot types',
              '40 shot selection points',
              '60 minutes partner communication play',
              '50 positioning scenarios',
              '5 games to 11 points',
              '6 games with varying effort levels',
              '4 games vs different opponents',
              '60 minutes multi-condition play',
              'Complete full-day simulation',
              '3 peak state activation sessions',
              '5 championship scenario games'
            ][i],
            tips: [
              ['Practice daily', 'Consistency is key', 'Build mental habits', 'Track progress'],
              ['Make it automatic', 'Same every time', 'Builds confidence', 'Reduces anxiety'],
              ['Short and effective', 'Helps reset mentally', 'Maintain composure', 'Stay present'],
              ['Embrace pressure', 'Practice is harder than matches', 'Build pressure tolerance', 'Stay calm'],
              ['Be detailed in imagery', 'Use all senses', 'Feel the success', 'Build neural pathways'],
              ['Minimize mental wandering', 'Return to present', 'Single-point focus', 'Sustain attention'],
              ['Expect mistakes', 'Have reset routine', 'Short memory', 'Next point mindset'],
              ['Match rally intensity', 'Work to rest ratio', 'Build capacity', 'Progressive overload'],
              ['Mental and physical stamina', 'Push through fatigue', 'Maintain quality', 'Build toughness'],
              ['Essential for tournaments', 'Multiple matches per day', 'Quick turnaround', 'Maximize recovery'],
              ['Quality over quantity', 'Track success rate', 'Build reliability', 'Pressure-proof skills'],
              ['Make smart choices', 'Think percentage pickleball', 'High-reward decisions', 'Minimize errors'],
              ['Over-communicate', 'Constant dialogue', 'Build chemistry', 'Prevent confusion'],
              ['Right place, right time', 'Anticipation', 'Court coverage', 'Team coordination'],
              ['Just like tournaments', 'Full intensity', 'Competitive mindset', 'Build match toughness'],
              ['Smart energy management', 'Know when to push', 'Know when to conserve', 'Win the tournament'],
              ['Scouting on the fly', 'Quick adjustments', 'Exploit weaknesses', 'Versatile game'],
              ['Adaptability crucial', 'Adjust technique', 'Mental flexibility', 'Environmental mastery'],
              ['Routine reduces anxiety', 'Everything planned', 'Nothing left to chance', 'Maximize readiness'],
              ['Find your zone', 'Optimal arousal', 'Maximum performance', 'Unlock potential'],
              ['Expect to win', 'Deserve success', 'Play your best', 'Claim the title']
            ][i]
          },
          {
            name: `Secondary Training - Day ${i + 1}`,
            description: [
              'Journaling: write pre-tournament goals, affirmations, and mental preparation notes.',
              'Video review: watch yourself play, identify pre-match routine effectiveness.',
              'Ritual refinement: test different between-point routines, find what works.',
              'Pressure exposure: play in front of crowd, have friends watch, simulate tournament pressure.',
              'Success journal: record visualizations, track confidence levels.',
              'Meditation practice: build ability to return focus quickly.',
              'Failure recovery: intentionally miss shots, practice mental bounce-back.',
              'Fitness testing: measure current fitness levels, set improvement goals.',
              'Long rally training: 50+ shot rallies, maintain quality throughout.',
              'Massage and mobility: active recovery session.',
              'Skills video analysis: review and correct technical inconsistencies.',
              'Decision-making games: quick-fire shot selection scenarios.',
              'Non-verbal communication: develop signals and body language with partner.',
              'Formation drills: practice switching formations smoothly.',
              'Match recording: video your simulations, watch and analyze.',
              'Energy system training: train all three energy systems used in pickleball.',
              'Style variety: play vs bangers, vs dinkers, vs all-court players.',
              'Equipment testing: try different paddles, balls in various conditions.',
              'Nutrition planning: perfect your tournament day meal plan.',
              'Mental triggers: develop phrases or actions that trigger peak state.',
              'Champion interview: practice post-match interviews and speeches.'
            ][i],
            duration_minutes: 15,
            reps_or_sets: [
              '15 minutes journaling',
              '20 minutes video analysis',
              '30 minutes ritual testing',
              '45 minutes public play',
              '15 minutes success documentation',
              '20 minutes meditation',
              '30 points failure recovery',
              '45 minutes fitness assessment',
              '3 rallies of 50+ shots',
              '30 minutes massage/mobility',
              '30 minutes video review',
              '50 quick scenarios',
              '30 minutes signal development',
              '40 formation transitions',
              'Full match recording',
              '40 minutes energy system work',
              '3 games vs each style',
              '60 minutes equipment testing',
              'Complete nutrition planning',
              '20 minutes trigger development',
              '15 minutes interview practice'
            ][i],
            tips: [
              ['Be honest', 'Track patterns', 'Identify growth areas', 'Build self-awareness'],
              ['Watch for habits', 'Note what works', 'Adjust routine', 'Continuous improvement'],
              ['Test under stress', 'Keep what works', 'Discard what doesn\'t', 'Personalize it'],
              ['Get comfortable uncomfortable', 'Public play builds immunity', 'Practice makes perfect', 'Fear reduction'],
              ['Document wins', 'Build confidence bank', 'Review before matches', 'Positive focus'],
              ['Daily practice', 'Even 5 minutes helps', 'Build focus muscle', 'Tournament essential'],
              ['Make mistakes on purpose', 'Practice recovery', 'Build resilience', 'Short memory'],
              ['Baseline assessment', 'Track improvement', 'Celebrate progress', 'Stay motivated'],
              ['Mental endurance test', 'Maintain focus', 'Quality under fatigue', 'Championship requirement'],
              ['Prevention is key', 'Stay fresh', 'Avoid injury', 'Perform better'],
              ['Self-coaching tool', 'Identify inconsistencies', 'Make corrections', 'Build reliability'],
              ['Trust your instincts', 'Train decision speed', 'Pattern recognition', 'Match IQ'],
              ['Silent communication', 'Tournament settings are loud', 'Backup communication', 'Seamless coordination'],
              ['Fluidity in changes', 'Confuse opponents', 'Tactical advantage', 'Practiced flexibility'],
              ['Video review tool', 'See yourself play', 'Learning accelerator', 'Performance insights'],
              ['Complete conditioning', 'Anaerobic capacity', 'Aerobic base', 'Recovery ability'],
              ['Versatile game', 'No weaknesses', 'Comfortable vs any style', 'Adaptable player'],
              ['Know your gear', 'Prepared for anything', 'Confidence in equipment', 'No surprises'],
              ['Nutrition impacts performance', 'Practice what works', 'Tournament day perfected', 'Energy optimization'],
              ['Instant state change', 'Anchor peak state', 'Reliable trigger', 'Performance on demand'],
              ['Expect to win', 'Comfortable with success', 'Handle victory well', 'Champion mentality']
            ][i]
          }
        ],
        practice_goals: [
          'Develop consistent mental preparation routine',
          'Perfect pre-match routine that builds confidence',
          'Master between-point reset ritual',
          'Build pressure tolerance through exposure',
          'Use visualization to enhance confidence',
          'Maintain focus for entire matches',
          'Develop ability to recover from setbacks',
          'Achieve target fitness levels for tournaments',
          'Build stamina for all-day tournaments',
          'Master recovery for multiple-match days',
          'Execute all shots consistently under pressure',
          'Make high-percentage shot selections',
          'Communicate seamlessly with partner',
          'Position correctly in all situations',
          'Perform well in match simulation',
          'Understand energy management for brackets',
          'Successfully adapt to different opponents',
          'Handle various playing conditions',
          'Establish effective tournament day routine',
          'Reliably achieve peak performance state',
          'Develop champion mindset and confidence'
        ][i],
        success_metrics: [
          'Mental routine practiced daily and effective',
          'Pre-match routine builds confidence consistently',
          'Between-point ritual helps maintain composure',
          'Perform well under simulated pressure',
          'Visualization improves confidence scores',
          'Maintain focus for 60+ minute matches',
          'Quick recovery from mistakes and losses',
          'Fitness tests show significant improvement',
          'Maintain performance quality through fatigue',
          'Recover effectively between matches',
          'Consistency maintained under pressure',
          'Smart shot selections win points',
          'Zero communication breakdowns',
          'Correct positioning 90%+ of time',
          'Win 60%+ of simulation games',
          'Successfully manage energy through bracket',
          'Adjust and win against various styles',
          'Perform well in all conditions',
          'Tournament routine reduces anxiety',
          'Peak state accessed reliably',
          'Champion mindset evident in play'
        ][i],
        cooldown: [
          'Mental relaxation exercises',
          'Full body stretching routine',
          'Recovery nutrition',
          'Hydration protocol',
          'Performance journaling',
          'Goal review and adjustment'
        ],
        coach_notes: [
          'Mental preparation is half the battle. Start building your mental game now!',
          'A solid pre-match routine eliminates uncertainty and builds confidence.',
          'Between-point rituals help you play one point at a time - the key to winning.',
          'Pressure is a privilege. Learn to love it through practice.',
          'Visualization works. The brain doesn\'t distinguish between imagined and real success.',
          'Focus is a skill you can train. It determines your ceiling as a player.',
          'Resilience separates winners from everyone else. Bouncing back is everything.',
          'You can\'t win tournaments without fitness. Make conditioning a priority.',
          'Stamina allows you to maintain your A-game when opponents fade.',
          'Recovery is when you actually improve. Master it for tournament success.',
          'Consistency under pressure wins championships. Train it specifically.',
          'Smart shot selection beats athletic ability. Think your way to wins.',
          'Great teams communicate constantly. Over-communicate and dominate.',
          'Positioning is often more important than shots. Be in the right place.',
          'Simulations build match toughness. Train harder than you compete.',
          'Tournaments are won by smart energy management, not going all-out every game.',
          'The best players adapt. Be comfortable playing multiple styles.',
          'Conditions change. Adaptable players win in any environment.',
          'A good routine calms nerves and maximizes readiness. Perfect yours.',
          'Peak performance is a state you can learn to access. Train the trigger.',
          'Congratulations! You\'re now tournament-ready. You have the skills, fitness, and mentality to compete at the highest levels. Go win!'
        ][i],
        estimated_minutes: 60,
        difficulty_level: 7 + Math.floor(i / 7)
      };
    })
  }
}
