
import { getServerSession } from 'next-auth/next'
import { authOptions } from '@/lib/auth'
import { redirect } from 'next/navigation'
import { prisma as db } from '@/lib/db'
import RedesignedHomeDashboard from '@/components/pages/redesigned-home-dashboard'

export const dynamic = 'force-dynamic'
export const revalidate = 0 // Always fetch fresh data

async function getUserPrograms(userId: string) {
  try {
    return await db.userProgram.findMany({
      where: { userId },
      include: {
        program: true
      },
      orderBy: { createdAt: 'desc' }
    })
  } catch (error) {
    console.error('Error fetching user programs:', error)
    return []
  }
}

async function getRecentActivity(userId: string) {
  try {
    return await db.trainingSessionActivity.findMany({
      where: { userId },
      orderBy: { sessionDate: 'desc' },
      take: 10
    })
  } catch (error) {
    console.error('Error fetching recent activity:', error)
    return []
  }
}

async function getUserAchievements(userId: string) {
  try {
    return await db.userAchievement.findMany({
      where: { userId },
      take: 5
    })
  } catch (error) {
    console.error('Error fetching achievements:', error)
    return []
  }
}

export default async function DashboardPage() {
  const session = await getServerSession(authOptions)
  
  if (!session?.user) {
    console.log('[Dashboard] No session found, redirecting to signin')
    redirect('/auth/signin')
  }

  console.log('[Dashboard] Checking onboarding status for user:', session.user.id)

  // Check if user has completed onboarding - NEW users must complete it first
  const user = await db.user.findUnique({
    where: { id: session.user.id },
    select: { 
      onboardingCompleted: true,
      onboardingCompletedAt: true,
      email: true 
    }
  })

  console.log('[Dashboard] User onboarding status:', {
    id: session.user.id,
    email: user?.email,
    onboardingCompleted: user?.onboardingCompleted,
    onboardingCompletedAt: user?.onboardingCompletedAt
  })

  if (!user?.onboardingCompleted) {
    console.log('[Dashboard] Onboarding not completed, redirecting to /onboarding')
    redirect('/onboarding')
  }

  console.log('[Dashboard] Access granted, loading dashboard')

  // Fetch user data
  const [userPrograms, recentActivity, achievements] = await Promise.all([
    getUserPrograms(session.user.id),
    getRecentActivity(session.user.id),
    getUserAchievements(session.user.id)
  ])

  return (
    <RedesignedHomeDashboard
      user={session.user}
      userPrograms={userPrograms}
      recentActivity={recentActivity}
      recommendations={[]} // Will be generated by the component
      achievements={achievements}
      upcomingContent={[]} // Will be generated by the component
    />
  )
}
