import { NextResponse } from 'next/server';
import { PrismaClient, SkillLevel, TournamentStatus, TournamentFormat } from '@prisma/client';

const prisma = new PrismaClient();

/**
 * Admin endpoint to seed the production database with tournament data
 * Requires ADMIN_SECRET in Authorization header
 */
export async function POST(request: Request) {
  try {
    // Authentication check
    const authHeader = request.headers.get('authorization');
    const adminSecret = process.env.ADMIN_SECRET || 'change-this-in-production';
    
    if (authHeader !== `Bearer ${adminSecret}`) {
      return NextResponse.json(
        { error: 'Unauthorized - Invalid or missing admin secret' },
        { status: 401 }
      );
    }

    // Clear existing tournaments
    const deletedCount = await prisma.tournament.deleteMany({});
    console.log(`Deleted ${deletedCount.count} existing tournaments`);

    // Tournament data to seed
    const tournamentsToCreate = [
      {
        name: 'Miami Open Pickleball Championship',
        description: 'Join us for the premier pickleball event in South Florida! Featuring professional-grade courts, live entertainment, and over $50,000 in prize money. This tournament attracts top players from around the world.',
        city: 'Miami Beach',
        state: 'FL',
        venueName: 'Miami Beach Convention Center',
        startDate: new Date('2026-02-15'),
        endDate: new Date('2026-02-18'),
        registrationDeadline: new Date('2026-02-01'),
        maxParticipants: 256,
        currentRegistrations: 0,
        entryFee: 150.00,
        prizePool: 50000.00,
        skillLevels: [SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED, SkillLevel.PRO],
        format: [TournamentFormat.SINGLES, TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
        status: TournamentStatus.UPCOMING,
        imageUrl: 'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=800',
        organizerName: 'Florida Pickleball Association',
        organizerEmail: 'info@floridapickleball.org',
        organizerPhone: '305-555-0100',
      },
      {
        name: 'Austin City Limits Pickleball Classic',
        description: 'Experience pickleball in the heart of Texas! Three days of intense competition with music, food trucks, and the famous Austin atmosphere. All skill levels welcome.',
        city: 'Austin',
        state: 'TX',
        venueName: 'Zilker Park Sports Complex',
        startDate: new Date('2026-03-20'),
        endDate: new Date('2026-03-22'),
        registrationDeadline: new Date('2026-03-05'),
        maxParticipants: 200,
        currentRegistrations: 0,
        entryFee: 125.00,
        prizePool: 35000.00,
        skillLevels: [SkillLevel.BEGINNER, SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED],
        format: [TournamentFormat.SINGLES, TournamentFormat.DOUBLES],
        status: TournamentStatus.UPCOMING,
        imageUrl: 'https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=800',
        organizerName: 'Texas Pickleball League',
        organizerEmail: 'info@texaspickleball.com',
        organizerPhone: '512-555-0200',
      },
      {
        name: 'San Diego Coastal Cup',
        description: 'Play pickleball with an ocean view! This beachside tournament offers stunning views, perfect weather, and competitive play. Evening social events included.',
        city: 'San Diego',
        state: 'CA',
        venueName: 'La Jolla Beach & Tennis Club',
        startDate: new Date('2026-01-25'),
        endDate: new Date('2026-01-27'),
        registrationDeadline: new Date('2026-01-10'),
        maxParticipants: 180,
        currentRegistrations: 0,
        entryFee: 175.00,
        prizePool: 40000.00,
        skillLevels: [SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED, SkillLevel.PRO],
        format: [TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
        status: TournamentStatus.UPCOMING,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Pickleball_Pros.jpg/1200px-Pickleball_Pros.jpg',
        organizerName: 'California Coastal Pickleball',
        organizerEmail: 'info@coastalpickleball.com',
        organizerPhone: '858-555-0300',
      },
      {
        name: 'Denver Rocky Mountain Challenge',
        description: 'Compete at altitude! This high-elevation tournament tests your endurance and skill. Features include mountain views, craft beer tastings, and Rocky Mountain hospitality.',
        city: 'Denver',
        state: 'CO',
        venueName: 'Denver Tennis Center',
        startDate: new Date('2026-04-10'),
        endDate: new Date('2026-04-13'),
        registrationDeadline: new Date('2026-03-25'),
        maxParticipants: 160,
        currentRegistrations: 0,
        entryFee: 140.00,
        prizePool: 30000.00,
        skillLevels: [SkillLevel.BEGINNER, SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED],
        format: [TournamentFormat.SINGLES, TournamentFormat.DOUBLES],
        status: TournamentStatus.UPCOMING,
        imageUrl: 'https://images.unsplash.com/photo-1566577134770-3d85bb3a9cc4?w=800',
        organizerName: 'Rocky Mountain Pickleball Association',
        organizerEmail: 'info@rockymtnpickleball.org',
        organizerPhone: '303-555-0400',
      },
      {
        name: 'Phoenix Desert Challenge',
        description: 'Battle the heat and your opponents in this desert showdown! Indoor air-conditioned courts, professional lighting, and Arizona sunshine make this a must-play event.',
        city: 'Scottsdale',
        state: 'AZ',
        venueName: 'Scottsdale Ranch Recreation Center',
        startDate: new Date('2026-02-28'),
        endDate: new Date('2026-03-02'),
        registrationDeadline: new Date('2026-02-15'),
        maxParticipants: 140,
        currentRegistrations: 0,
        entryFee: 130.00,
        prizePool: 28000.00,
        skillLevels: [SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED],
        format: [TournamentFormat.SINGLES, TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
        status: TournamentStatus.UPCOMING,
        imageUrl: 'https://images.unsplash.com/photo-1575361204480-aadea25e6e68?w=800',
        organizerName: 'Arizona Pickleball Federation',
        organizerEmail: 'info@azpickleball.com',
        organizerPhone: '480-555-0500',
      },
      {
        name: 'Seattle Emerald City Open',
        description: 'Join the Pacific Northwest pickleball community for three days of competition in Seattle. Rain or shine (mostly rain), we play on! Indoor facilities with spectacular city views.',
        city: 'Seattle',
        state: 'WA',
        venueName: 'Seattle Tennis Center',
        startDate: new Date('2026-03-06'),
        endDate: new Date('2026-03-08'),
        registrationDeadline: new Date('2026-02-20'),
        maxParticipants: 190,
        currentRegistrations: 0,
        entryFee: 145.00,
        prizePool: 32000.00,
        skillLevels: [SkillLevel.BEGINNER, SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED, SkillLevel.PRO],
        format: [TournamentFormat.SINGLES, TournamentFormat.DOUBLES],
        status: TournamentStatus.UPCOMING,
        imageUrl: 'http://mvpvisuals.com/cdn/shop/articles/fun-pickleball-tournament-match-mvp-visuals_970213ca-a54e-432e-8dbc-80c0c9500571.png?v=1758823186',
        organizerName: 'Emerald City Pickleball Club',
        organizerEmail: 'info@seattlepickleball.org',
        organizerPhone: '206-555-0600',
      },
      {
        name: 'Chicago Windy City Classic',
        description: 'Americas heartland hosts one of the biggest pickleball tournaments of the year. State-of-the-art indoor facility, great food, and Midwest hospitality.',
        city: 'Chicago',
        state: 'IL',
        venueName: 'McFetridge Sports Center',
        startDate: new Date('2026-04-24'),
        endDate: new Date('2026-04-26'),
        registrationDeadline: new Date('2026-04-10'),
        maxParticipants: 220,
        currentRegistrations: 0,
        entryFee: 135.00,
        prizePool: 38000.00,
        skillLevels: [SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED, SkillLevel.PRO],
        format: [TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
        status: TournamentStatus.UPCOMING,
        imageUrl: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?w=800',
        organizerName: 'Windy City Pickleball Association',
        organizerEmail: 'info@chicagopickleball.com',
        organizerPhone: '312-555-0700',
      },
      {
        name: 'Atlanta Peachtree Open',
        description: 'Southern charm meets competitive pickleball! Join us in Atlanta for a weekend of great play, delicious Southern food, and live music. Y\'all come!',
        city: 'Atlanta',
        state: 'GA',
        venueName: 'Bitsy Grant Tennis Center',
        startDate: new Date('2026-05-08'),
        endDate: new Date('2026-05-10'),
        registrationDeadline: new Date('2026-04-22'),
        maxParticipants: 175,
        currentRegistrations: 0,
        entryFee: 120.00,
        prizePool: 25000.00,
        skillLevels: [SkillLevel.BEGINNER, SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED],
        format: [TournamentFormat.SINGLES, TournamentFormat.DOUBLES],
        status: TournamentStatus.UPCOMING,
        imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
        organizerName: 'Georgia Pickleball League',
        organizerEmail: 'info@georgiapickleball.org',
        organizerPhone: '404-555-0800',
      },
      {
        name: 'Boston New England Championship',
        description: 'Historic Boston hosts this prestigious tournament. Perfect spring weather, professional organization, and true New England charm. Wicked good pickleball!',
        city: 'Boston',
        state: 'MA',
        venueName: 'Boston Sports Complex',
        startDate: new Date('2026-05-22'),
        endDate: new Date('2026-05-24'),
        registrationDeadline: new Date('2026-05-05'),
        maxParticipants: 185,
        currentRegistrations: 0,
        entryFee: 155.00,
        prizePool: 35000.00,
        skillLevels: [SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED, SkillLevel.PRO],
        format: [TournamentFormat.SINGLES, TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
        status: TournamentStatus.UPCOMING,
        imageUrl: 'https://media.sportstravelmagazine.com/wp-content/uploads/2023/05/10023745/venue_IMG_3024-2-scaled.jpg',
        organizerName: 'New England Pickleball Federation',
        organizerEmail: 'info@nepickleball.com',
        organizerPhone: '617-555-0900',
      },
      {
        name: 'Las Vegas Desert Open',
        description: 'What happens in Vegas... gets recorded on tournament stats! Play during the day, enjoy world-class entertainment at night. The ultimate pickleball destination.',
        city: 'Las Vegas',
        state: 'NV',
        venueName: 'Las Vegas Sports Park',
        startDate: new Date('2026-06-05'),
        endDate: new Date('2026-06-08'),
        registrationDeadline: new Date('2026-05-20'),
        maxParticipants: 240,
        currentRegistrations: 0,
        entryFee: 180.00,
        prizePool: 60000.00,
        skillLevels: [SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED, SkillLevel.PRO],
        format: [TournamentFormat.SINGLES, TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
        status: TournamentStatus.UPCOMING,
        imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
        organizerName: 'Nevada Pickleball Association',
        organizerEmail: 'info@vegaspickleball.com',
        organizerPhone: '702-555-1000',
      },
      {
        name: 'Portland Rose City Classic',
        description: 'Keep Portland weird... and pickleballin! Eco-friendly tournament with sustainable practices, local food vendors, and the friendliest players on the West Coast.',
        city: 'Portland',
        state: 'OR',
        venueName: 'Portland Tennis Center',
        startDate: new Date('2026-06-19'),
        endDate: new Date('2026-06-21'),
        registrationDeadline: new Date('2026-06-05'),
        maxParticipants: 165,
        currentRegistrations: 0,
        entryFee: 125.00,
        prizePool: 27000.00,
        skillLevels: [SkillLevel.BEGINNER, SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED],
        format: [TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
        status: TournamentStatus.UPCOMING,
        imageUrl: 'https://www.shutterstock.com/image-vector/pickleball-tournament-flyer-logo-emblem-600w-2363824081.jpg',
        organizerName: 'Rose City Pickleball Club',
        organizerEmail: 'info@portlandpickleball.org',
        organizerPhone: '503-555-1100',
      },
      {
        name: 'Nashville Music City Open',
        description: 'Pickleball meets country music! Day courts overlook downtown Nashville, evening concerts feature local artists. Honky-tonk and dinking perfection.',
        city: 'Nashville',
        state: 'TN',
        venueName: 'Centennial SportsPlex',
        startDate: new Date('2026-07-10'),
        endDate: new Date('2026-07-12'),
        registrationDeadline: new Date('2026-06-25'),
        maxParticipants: 195,
        currentRegistrations: 0,
        entryFee: 140.00,
        prizePool: 33000.00,
        skillLevels: [SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED, SkillLevel.PRO],
        format: [TournamentFormat.SINGLES, TournamentFormat.DOUBLES],
        status: TournamentStatus.UPCOMING,
        imageUrl: 'https://www.sportico.com/wp-content/uploads/2023/03/GettyImages-1467778418-e1678653111733.jpg?w=1280&h=720&crop=1',
        organizerName: 'Tennessee Pickleball League',
        organizerEmail: 'info@nashvillepickleball.com',
        organizerPhone: '615-555-1200',
      },
      {
        name: 'Philadelphia Liberty Bell Classic',
        description: 'Historic Philadelphia hosts this patriotic tournament. Play where history was made, enjoy world-class museums, and savor authentic Philly cheesesteaks.',
        city: 'Philadelphia',
        state: 'PA',
        venueName: 'Penn Park Athletics Complex',
        startDate: new Date('2026-07-24'),
        endDate: new Date('2026-07-26'),
        registrationDeadline: new Date('2026-07-10'),
        maxParticipants: 170,
        currentRegistrations: 0,
        entryFee: 145.00,
        prizePool: 31000.00,
        skillLevels: [SkillLevel.BEGINNER, SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED],
        format: [TournamentFormat.SINGLES, TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
        status: TournamentStatus.UPCOMING,
        imageUrl: 'https://images.unsplash.com/photo-1536890992765-f42a1ee1e2a8?w=800',
        organizerName: 'Philadelphia Pickleball Association',
        organizerEmail: 'info@phillypickleball.org',
        organizerPhone: '215-555-1300',
      },
      {
        name: 'Minneapolis Lakes Classic',
        description: 'Land of 10,000 lakes, home to one amazing pickleball tournament! Beautiful summer weather, lakeside venues, and Minnesota nice hospitality.',
        city: 'Minneapolis',
        state: 'MN',
        venueName: 'Baseline Tennis Center',
        startDate: new Date('2026-08-07'),
        endDate: new Date('2026-08-09'),
        registrationDeadline: new Date('2026-07-20'),
        maxParticipants: 155,
        currentRegistrations: 0,
        entryFee: 130.00,
        prizePool: 26000.00,
        skillLevels: [SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED],
        format: [TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
        status: TournamentStatus.UPCOMING,
        imageUrl: 'https://images.unsplash.com/photo-1523821741446-edb2b68bb7a0?w=800',
        organizerName: 'Minnesota Pickleball Federation',
        organizerEmail: 'info@mnpickleball.org',
        organizerPhone: '612-555-1400',
      },
      {
        name: 'Charlotte Queen City Challenge',
        description: 'Southern charm with competitive edge! Charlotte offers modern facilities, great restaurants, and a growing pickleball community. Come for the tournament, stay for the city!',
        city: 'Charlotte',
        state: 'NC',
        venueName: 'Olde Providence Racquet Club',
        startDate: new Date('2026-08-21'),
        endDate: new Date('2026-08-23'),
        registrationDeadline: new Date('2026-08-05'),
        maxParticipants: 180,
        currentRegistrations: 0,
        entryFee: 135.00,
        prizePool: 29000.00,
        skillLevels: [SkillLevel.BEGINNER, SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED],
        format: [TournamentFormat.SINGLES, TournamentFormat.DOUBLES],
        status: TournamentStatus.UPCOMING,
        imageUrl: 'https://images.unsplash.com/photo-1558981359-219d6364c9c8?w=800',
        organizerName: 'Carolina Pickleball League',
        organizerEmail: 'info@carolinapickleball.com',
        organizerPhone: '704-555-1500',
      },
      {
        name: 'Columbus Buckeye Open',
        description: 'O-H-I-O! The Buckeye State hosts this family-friendly tournament. Perfect for players of all levels, with great facilities and Midwest hospitality.',
        city: 'Columbus',
        state: 'OH',
        venueName: 'Griggs Tennis Center',
        startDate: new Date('2026-09-04'),
        endDate: new Date('2026-09-06'),
        registrationDeadline: new Date('2026-08-20'),
        maxParticipants: 160,
        currentRegistrations: 0,
        entryFee: 120.00,
        prizePool: 24000.00,
        skillLevels: [SkillLevel.BEGINNER, SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED],
        format: [TournamentFormat.SINGLES, TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
        status: TournamentStatus.UPCOMING,
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1f/Pickleball_Players.jpg',
        organizerName: 'Ohio Pickleball Association',
        organizerEmail: 'info@ohiopickleball.org',
        organizerPhone: '614-555-1600',
      },
      {
        name: 'New Orleans Bayou Classic',
        description: 'Laissez les bons temps rouler! Pickleball NOLA style with live jazz, amazing Cajun food, and the most fun youll have at a tournament. Who dat say dey gonna beat us?',
        city: 'New Orleans',
        state: 'LA',
        venueName: 'City Park Tennis Center',
        startDate: new Date('2026-09-18'),
        endDate: new Date('2026-09-20'),
        registrationDeadline: new Date('2026-09-05'),
        maxParticipants: 145,
        currentRegistrations: 0,
        entryFee: 150.00,
        prizePool: 32000.00,
        skillLevels: [SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED, SkillLevel.PRO],
        format: [TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
        status: TournamentStatus.UPCOMING,
        imageUrl: 'https://static01.nyt.com/images/2024/11/14/multimedia/06PICKLEBALL-CHAMPIONSHIP-01-vblc/06PICKLEBALL-CHAMPIONSHIP-01-vblc-videoSixteenByNineJumbo1600.jpg',
        organizerName: 'Louisiana Pickleball Federation',
        organizerEmail: 'info@nolpickleball.com',
        organizerPhone: '504-555-1700',
      },
      {
        name: 'Salt Lake City Mountain West Open',
        description: 'Greatest snow on earth, greatest pickleball in the Rockies! High altitude training meets competitive play. Stunning mountain backdrop included.',
        city: 'Salt Lake City',
        state: 'UT',
        venueName: 'Liberty Park Tennis Center',
        startDate: new Date('2026-10-02'),
        endDate: new Date('2026-10-04'),
        registrationDeadline: new Date('2026-09-15'),
        maxParticipants: 150,
        currentRegistrations: 0,
        entryFee: 140.00,
        prizePool: 28000.00,
        skillLevels: [SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED],
        format: [TournamentFormat.SINGLES, TournamentFormat.DOUBLES],
        status: TournamentStatus.UPCOMING,
        imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
        organizerName: 'Utah Pickleball Association',
        organizerEmail: 'info@utahpickleball.org',
        organizerPhone: '801-555-1800',
      },
      {
        name: 'Albuquerque Balloon Fiesta Classic',
        description: 'Time your visit with the famous Balloon Fiesta! Watch hot air balloons while playing competitive pickleball. Southwest cuisine and culture abound.',
        city: 'Albuquerque',
        state: 'NM',
        venueName: 'Jerry Cline Tennis Complex',
        startDate: new Date('2026-10-16'),
        endDate: new Date('2026-10-18'),
        registrationDeadline: new Date('2026-10-01'),
        maxParticipants: 135,
        currentRegistrations: 0,
        entryFee: 125.00,
        prizePool: 22000.00,
        skillLevels: [SkillLevel.BEGINNER, SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED],
        format: [TournamentFormat.SINGLES, TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
        status: TournamentStatus.UPCOMING,
        imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
        organizerName: 'New Mexico Pickleball League',
        organizerEmail: 'info@nmpickleball.com',
        organizerPhone: '505-555-1900',
      },
      {
        name: 'Kansas City Heartland Championship',
        description: 'Americas heartland, Americas pickleball! Famous BBQ, friendly people, and great competition make this a tournament you wont want to miss.',
        city: 'Kansas City',
        state: 'MO',
        venueName: 'Swope Park Tennis Center',
        startDate: new Date('2026-10-30'),
        endDate: new Date('2026-11-01'),
        registrationDeadline: new Date('2026-10-15'),
        maxParticipants: 165,
        currentRegistrations: 0,
        entryFee: 130.00,
        prizePool: 27000.00,
        skillLevels: [SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED],
        format: [TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
        status: TournamentStatus.UPCOMING,
        imageUrl: 'https://images.unsplash.com/photo-1566577134770-3d85bb3a9cc4?w=800',
        organizerName: 'Kansas City Pickleball Club',
        organizerEmail: 'info@kcpickleball.org',
        organizerPhone: '816-555-2000',
      },
      {
        name: 'Indianapolis Hoosier Classic',
        description: 'Racing capital meets pickleball! Fast-paced action on and off the court. Indoor facilities ensure perfect playing conditions year-round.',
        city: 'Indianapolis',
        state: 'IN',
        venueName: 'Indianapolis Tennis Center',
        startDate: new Date('2026-11-13'),
        endDate: new Date('2026-11-15'),
        registrationDeadline: new Date('2026-10-28'),
        maxParticipants: 175,
        currentRegistrations: 0,
        entryFee: 135.00,
        prizePool: 30000.00,
        skillLevels: [SkillLevel.BEGINNER, SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED, SkillLevel.PRO],
        format: [TournamentFormat.SINGLES, TournamentFormat.DOUBLES],
        status: TournamentStatus.UPCOMING,
        imageUrl: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?w=800',
        organizerName: 'Indiana Pickleball Federation',
        organizerEmail: 'info@indianapickleball.org',
        organizerPhone: '317-555-2100',
      },
      {
        name: 'Richmond Virginia State Championship',
        description: 'Commonwealth pickleball at its finest! Historic Richmond hosts this prestigious state championship with colonial charm and modern facilities.',
        city: 'Richmond',
        state: 'VA',
        venueName: 'Richmond Racquet Club',
        startDate: new Date('2026-11-27'),
        endDate: new Date('2026-11-29'),
        registrationDeadline: new Date('2026-11-10'),
        maxParticipants: 155,
        currentRegistrations: 0,
        entryFee: 140.00,
        prizePool: 28000.00,
        skillLevels: [SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED, SkillLevel.PRO],
        format: [TournamentFormat.SINGLES, TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
        status: TournamentStatus.UPCOMING,
        imageUrl: 'https://media.gettyimages.com/id/2197474761/photo/hispanic-friends-playing-pickleball.jpg?s=612x612&w=gi&k=20&c=JN_iFusYlc-E2HBnGT2y7EDI9pmY8J2D34zH944ITWE=',
        organizerName: 'Virginia Pickleball Association',
        organizerEmail: 'info@virginiapickleball.org',
        organizerPhone: '804-555-2200',
      },
      {
        name: 'Milwaukee Winter Classic',
        description: 'Indoor tournament during Milwaukees winter! Heated facilities, local craft beer tastings, and cheese curds galore. Bring your A-game and appetite!',
        city: 'Milwaukee',
        state: 'WI',
        venueName: 'Uihlein Tennis Center',
        startDate: new Date('2026-12-11'),
        endDate: new Date('2026-12-13'),
        registrationDeadline: new Date('2026-11-25'),
        maxParticipants: 145,
        currentRegistrations: 0,
        entryFee: 125.00,
        prizePool: 25000.00,
        skillLevels: [SkillLevel.BEGINNER, SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED],
        format: [TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
        status: TournamentStatus.UPCOMING,
        imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
        organizerName: 'Wisconsin Pickleball League',
        organizerEmail: 'info@wipickleball.org',
        organizerPhone: '414-555-2300',
      },
      {
        name: 'Honolulu Island Paradise Classic',
        description: 'Aloha! End the year with pickleball in paradise! Play on outdoor courts with ocean breezes, enjoy Hawaiian culture, and experience true aloha spirit.',
        city: 'Honolulu',
        state: 'HI',
        venueName: 'Ala Moana Beach Park',
        startDate: new Date('2026-12-27'),
        endDate: new Date('2026-12-30'),
        registrationDeadline: new Date('2026-12-10'),
        maxParticipants: 200,
        currentRegistrations: 0,
        entryFee: 200.00,
        prizePool: 45000.00,
        skillLevels: [SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED, SkillLevel.PRO],
        format: [TournamentFormat.SINGLES, TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
        status: TournamentStatus.UPCOMING,
        imageUrl: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
        organizerName: 'Hawaii Pickleball Association',
        organizerEmail: 'info@hawaiipickleball.org',
        organizerPhone: '808-555-2400',
      },
      {
        name: 'Tampa Bay Sunshine Invitational',
        description: 'Start the new year with sunshine and pickleball! Tampa Bay offers perfect weather, beachside venues, and a vibrant pickleball community.',
        city: 'Tampa',
        state: 'FL',
        venueName: 'HCC Dale Mabry Campus',
        startDate: new Date('2026-01-15'),
        endDate: new Date('2026-01-17'),
        registrationDeadline: new Date('2026-01-01'),
        maxParticipants: 185,
        currentRegistrations: 0,
        entryFee: 145.00,
        prizePool: 34000.00,
        skillLevels: [SkillLevel.BEGINNER, SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED],
        format: [TournamentFormat.SINGLES, TournamentFormat.DOUBLES],
        status: TournamentStatus.UPCOMING,
        imageUrl: 'https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=800',
        organizerName: 'Tampa Bay Pickleball Club',
        organizerEmail: 'info@tampapickleball.com',
        organizerPhone: '813-555-2500',
      },
      {
        name: 'Dallas Fort Worth Metroplex Championship',
        description: 'Everything is bigger in Texas, including our pickleball tournament! DFW hosts this mega-event with top players, huge prize pool, and Texas-sized fun.',
        city: 'Dallas',
        state: 'TX',
        venueName: 'Lifetime Fitness - Plano',
        startDate: new Date('2026-04-17'),
        endDate: new Date('2026-04-19'),
        registrationDeadline: new Date('2026-04-01'),
        maxParticipants: 230,
        currentRegistrations: 0,
        entryFee: 165.00,
        prizePool: 42000.00,
        skillLevels: [SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED, SkillLevel.PRO],
        format: [TournamentFormat.SINGLES, TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
        status: TournamentStatus.UPCOMING,
        imageUrl: 'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=800',
        organizerName: 'DFW Pickleball Association',
        organizerEmail: 'info@dfwpickleball.com',
        organizerPhone: '214-555-2600',
      },
      {
        name: 'San Antonio Riverwalk Classic',
        description: 'Play pickleball on the famous San Antonio Riverwalk! Scenic venues, delicious Tex-Mex, and the Alamo make this a memorable tournament experience.',
        city: 'San Antonio',
        state: 'TX',
        venueName: 'McFarlin Tennis Center',
        startDate: new Date('2026-05-01'),
        endDate: new Date('2026-05-03'),
        registrationDeadline: new Date('2026-04-15'),
        maxParticipants: 170,
        currentRegistrations: 0,
        entryFee: 135.00,
        prizePool: 29000.00,
        skillLevels: [SkillLevel.BEGINNER, SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED],
        format: [TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
        status: TournamentStatus.UPCOMING,
        imageUrl: 'https://sonicpromos.com/wp-content/uploads/2024/05/Magz.png',
        organizerName: 'Alamo City Pickleball League',
        organizerEmail: 'info@satxpickleball.org',
        organizerPhone: '210-555-2700',
      },
      {
        name: 'Sacramento Capital Challenge',
        description: 'Californias capital hosts this competitive tournament! Farm-to-table food, craft beverages, and excellent playing conditions in the heart of the Central Valley.',
        city: 'Sacramento',
        state: 'CA',
        venueName: 'Capitol Park Tennis Complex',
        startDate: new Date('2026-06-12'),
        endDate: new Date('2026-06-14'),
        registrationDeadline: new Date('2026-05-28'),
        maxParticipants: 160,
        currentRegistrations: 0,
        entryFee: 150.00,
        prizePool: 31000.00,
        skillLevels: [SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED, SkillLevel.PRO],
        format: [TournamentFormat.SINGLES, TournamentFormat.DOUBLES],
        status: TournamentStatus.UPCOMING,
        imageUrl: 'https://images.unsplash.com/photo-1575361204480-aadea25e6e68?w=800',
        organizerName: 'Sacramento Valley Pickleball',
        organizerEmail: 'info@sacpickleball.com',
        organizerPhone: '916-555-2800',
      },
      {
        name: 'Tucson Desert Sun Classic',
        description: 'Beautiful Tucson welcomes pickleballers from around the country! Desert scenery, Southwestern hospitality, and top-notch competition await.',
        city: 'Tucson',
        state: 'AZ',
        venueName: 'Tucson Racquet Club',
        startDate: new Date('2026-03-13'),
        endDate: new Date('2026-03-15'),
        registrationDeadline: new Date('2026-02-25'),
        maxParticipants: 150,
        currentRegistrations: 0,
        entryFee: 130.00,
        prizePool: 26000.00,
        skillLevels: [SkillLevel.BEGINNER, SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED],
        format: [TournamentFormat.SINGLES, TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
        status: TournamentStatus.UPCOMING,
        imageUrl: 'https://media.istockphoto.com/id/1690705632/vector/pickleball-tournament.jpg?s=612x612&w=0&k=20&c=UvehbJtqP_x-f1pKEsy_T1iHFSQ8JiMiiHoTs5MjQDs=',
        organizerName: 'Southern Arizona Pickleball',
        organizerEmail: 'info@tucsonpickleball.org',
        organizerPhone: '520-555-2900',
      },
      {
        name: 'Oklahoma City Heartland Open',
        description: 'OK is OK for pickleball! Friendly competition in the heart of Oklahoma with down-home hospitality and great facilities. Yall come play!',
        city: 'Oklahoma City',
        state: 'OK',
        venueName: 'OKC Tennis Center',
        startDate: new Date('2026-09-25'),
        endDate: new Date('2026-09-27'),
        registrationDeadline: new Date('2026-09-10'),
        maxParticipants: 140,
        currentRegistrations: 0,
        entryFee: 120.00,
        prizePool: 23000.00,
        skillLevels: [SkillLevel.INTERMEDIATE, SkillLevel.ADVANCED],
        format: [TournamentFormat.DOUBLES, TournamentFormat.MIXED_DOUBLES],
        status: TournamentStatus.UPCOMING,
        imageUrl: 'https://thumbs.dreamstime.com/b/pickleball-gear-accessories-flat-illustration-clean-flat-illustration-showcasing-essential-pickleball-equipment-412129292.jpg',
        organizerName: 'Oklahoma Pickleball Association',
        organizerEmail: 'info@okpickleball.org',
        organizerPhone: '405-555-3000',
      },
    ];

    // Create all tournaments
    let successCount = 0;
    let failureCount = 0;

    for (const tournament of tournamentsToCreate) {
      try {
        await prisma.tournament.create({ data: tournament });
        successCount++;
      } catch (error) {
        console.error(`Failed to create tournament: ${tournament.name}`, error);
        failureCount++;
      }
    }

    const finalCount = await prisma.tournament.count();
    
    console.log(`\nSeeding complete:`);
    console.log(`  - Successful: ${successCount}`);
    console.log(`  - Failed: ${failureCount}`);
    console.log(`  - Total in database: ${finalCount}`);
    
    return NextResponse.json({ 
      success: true,
      message: `Successfully seeded ${successCount} tournaments`,
      stats: {
        created: successCount,
        failed: failureCount,
        total: finalCount,
      },
      timestamp: new Date().toISOString(),
    });
  } catch (error) {
    console.error('Seeding error:', error);
    return NextResponse.json(
      { 
        success: false,
        error: 'Seeding failed',
        message: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    );
  } finally {
    await prisma.$disconnect();
  }
}
